"""``satk re export ghidra|x32dbg|json`` (SPEC §4.9.3; owner WP-09).

Exports go to ``work/re/export/`` (never into the repository):

* ``json``   -> ``symbols.json``: functions, globals, vtables, thunks, patches (column lists + rows);
* ``x32dbg`` -> ``gta_sa.exe.dd32``: an x64dbg/x32dbg database with labels (functions, globals,
  vtables) and comments (source ``file:line``, MTA patches) keyed by module RVA;
* ``ghidra`` -> ``ApplySaSymbols.py`` + ``symbols.json``: a Ghidra script (Jython or PyGhidra) that
  names functions (with class namespaces), labels globals/vtables and adds plate comments.
"""

from __future__ import annotations

import json
from pathlib import Path

from ..core.paths import atomic_write, ensure_writable, jpath, work
from .db import SymDb, hx

__all__ = ["export", "symbols_payload", "GHIDRA_SCRIPT"]


def symbols_payload(db: SymDb) -> dict:
    con = db.con
    funcs = [[hx(r["addr"]), hx(r["end_addr"]), r["qual"], (f"{r['src_file']}:{r['src_line']}" if r["src_file"] else None),
              r["reversed"], r["origin"]]
             for r in con.execute("SELECT * FROM func WHERE qual IS NOT NULL ORDER BY addr")]
    globs = [[hx(r["addr"]), r["name"], r["type"], r["array_len"], r["byte_size"],
              (f"{r['src_file']}:{r['src_line']}" if r["src_file"] else None)]
             for r in con.execute("SELECT * FROM global ORDER BY addr")]
    vts = [[hx(r["addr"]), r["cls"], r["slots"]] for r in con.execute("SELECT * FROM vtable ORDER BY addr")]
    thunks = [[hx(r["addr"]), hx(r["target"]), r["kind"]] for r in con.execute("SELECT * FROM thunk ORDER BY addr")]
    patches = [[hx(r["addr"]), r["len"], r["kind"], r["symbol"], r["origin"], f"{r['src_file']}:{r['src_line']}"]
               for r in con.execute("SELECT * FROM patch ORDER BY addr, origin")]
    return {
        "format": "satk-symbols/1",
        "image_base": db.meta.get("image_base", "0x400000"),
        "exe_sha256": db.meta.get("exe_sha256"),
        "built_at": db.meta.get("built_at"),
        "sources": db.sources(),
        "functions": {"cols": ["addr", "end", "name", "src", "reversed", "origin"], "rows": funcs},
        "globals": {"cols": ["addr", "name", "type", "array_len", "byte_size", "src"], "rows": globs},
        "vtables": {"cols": ["addr", "cls", "slots"], "rows": vts},
        "thunks": {"cols": ["addr", "target", "kind"], "rows": thunks},
        "patches": {"cols": ["addr", "len", "kind", "symbol", "origin", "src"], "rows": patches},
    }


def _x32dbg(db: SymDb, payload: dict) -> dict:
    base = int(payload["image_base"], 16)
    mod = "gta_sa.exe"

    def rva(a: str) -> str:
        return f"0x{int(a, 16) - base:X}"

    labels, comments, functions = [], [], []
    for addr, end, name, src, _rev, _origin in payload["functions"]["rows"]:
        labels.append({"module": mod, "address": rva(addr), "manual": True, "text": name})
        if src:
            comments.append({"module": mod, "address": rva(addr), "manual": True, "text": src})
        if end and int(end, 16) > int(addr, 16):
            functions.append({"module": mod, "start": rva(addr), "end": f"0x{int(end, 16) - 1 - base:X}",
                              "manual": True, "icount": 0})
    for addr, name, *_rest in payload["globals"]["rows"]:
        labels.append({"module": mod, "address": rva(addr), "manual": True, "text": name})
    for addr, cls, _slots in payload["vtables"]["rows"]:
        labels.append({"module": mod, "address": rva(addr), "manual": True, "text": f"vtbl_{cls}"})
    seen: dict[str, list[str]] = {}
    for addr, _len, kind, symbol, origin, _src in payload["patches"]["rows"]:
        seen.setdefault(addr, []).append(f"{origin}:{symbol or kind}")
    for addr, notes in seen.items():
        comments.append({"module": mod, "address": rva(addr), "manual": True,
                         "text": "MTA " + ", ".join(sorted(set(notes)))[:240]})
    return {"labels": labels, "comments": comments, "functions": functions}


GHIDRA_SCRIPT = r'''# ApplySaSymbols.py - generated by satk (satk re export ghidra). Applies sa-re symbols to gta_sa.exe.
# @category satk
# Run from Ghidra (Script Manager) or headless: -postScript ApplySaSymbols.py
# Reads symbols.json from the same directory. Works with Jython (Ghidra <= 11) and PyGhidra (12+).
import json
import os

try:
    from ghidra.program.model.symbol import SourceType
    from ghidra.app.util import NamespaceUtils
except ImportError:  # pragma: no cover - only inside Ghidra
    raise SystemExit("run this script inside Ghidra")

try:
    HERE = os.path.dirname(str(getSourceFile().getAbsolutePath()))
except Exception:
    HERE = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(HERE, "symbols.json")) as f:
    DATA = json.load(f)

prog = currentProgram
fm = prog.getFunctionManager()
st = prog.getSymbolTable()
listing = prog.getListing()
USER = SourceType.USER_DEFINED


def addr(h):
    return toAddr(int(h, 16))


def ns_for(qual):
    if "::" not in qual:
        return None, qual
    parts = qual.split("::")
    try:
        ns = NamespaceUtils.createNamespaceHierarchy("::".join(parts[:-1]), None, prog, USER)
        return ns, parts[-1]
    except Exception:
        return None, qual.replace("::", "__")


n_fn = n_lbl = 0
for a, end, name, src, rev, origin in DATA["functions"]["rows"]:
    ad = addr(a)
    fn = fm.getFunctionAt(ad)
    if fn is None:
        try:
            fn = createFunction(ad, None)
        except Exception:
            fn = None
    ns, short = ns_for(name)
    try:
        if fn is not None:
            if ns is not None:
                fn.setParentNamespace(ns)
            fn.setName(short.replace(" ", "_"), USER)
            n_fn += 1
        else:
            st.createLabel(ad, short.replace(" ", "_"), ns, USER)
            n_lbl += 1
        if src:
            listing.setComment(ad, 3, "%s (%s)" % (src, origin))  # 3 = PLATE_COMMENT
    except Exception as e:  # keep going on odd names
        print("skip %s %s: %s" % (a, name, e))

for a, name, typ, alen, size, src in DATA["globals"]["rows"]:
    ns, short = ns_for(name)
    try:
        st.createLabel(addr(a), short, ns, USER)
        n_lbl += 1
    except Exception as e:
        print("skip global %s %s: %s" % (a, name, e))

for a, cls, slots in DATA["vtables"]["rows"]:
    try:
        st.createLabel(addr(a), "vtbl_" + cls.replace("::", "__"), USER)
        n_lbl += 1
    except Exception as e:
        print("skip vtable %s: %s" % (a, e))

print("satk: %d functions named, %d labels" % (n_fn, n_lbl))
'''


def export(db: SymDb, fmt: str, out: str | None = None) -> dict:
    """Write the export files; returns ``{files, counts}``."""
    out_dir = Path(out) if out else work("re", "export")
    ensure_writable(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    payload = symbols_payload(db)
    counts = {k: len(payload[k]["rows"]) for k in ("functions", "globals", "vtables", "thunks", "patches")}
    files: list[Path] = []
    if fmt == "json":
        files.append(atomic_write(out_dir / "symbols.json", json.dumps(payload, separators=(",", ":"))))
    elif fmt == "x32dbg":
        dd = _x32dbg(db, payload)
        files.append(atomic_write(out_dir / "gta_sa.exe.dd32", json.dumps(dd, indent=1)))
        counts.update(labels=len(dd["labels"]), comments=len(dd["comments"]))
    elif fmt == "ghidra":
        gdir = out_dir / "ghidra"
        files.append(atomic_write(gdir / "symbols.json", json.dumps(payload, separators=(",", ":"))))
        files.append(atomic_write(gdir / "ApplySaSymbols.py", GHIDRA_SCRIPT))
    else:  # pragma: no cover - guarded by the Literal parameter
        raise ValueError(fmt)
    return {"files": [jpath(p) for p in files], "counts": counts}
