"""An MTA:SA client resource that loads an IFP and replaces game animations (``satk anim mta``). Stdlib only.

The resource (``<work>/out/anim/mta/<name>/``) holds ``meta.xml``, ``client.lua`` and the IFP. ``client.lua`` calls
``engineLoadIFP(file, block)`` once and ``engineReplaceAnimation(ped, game block, game anim, block, custom anim)``
for every streamed-in player and ped (a game block that is not loaded yet is requested by the first call, which
returns false: the script retries a few times), and ``engineRestoreAnimation`` when the resource stops. MTA reads
ANP3, ANP2 and ANPK files (``CClientIFP``); the IFP is copied as it is.
"""

from __future__ import annotations

from dataclasses import dataclass

__all__ = ["Replace", "parse_replace", "lua_str", "client_lua", "meta_xml"]


@dataclass(frozen=True)
class Replace:
    """``engineReplaceAnimation`` arguments: game block and animation -> custom animation of the loaded block."""

    block: str
    anim: str
    custom: str


def parse_replace(item: str, default_block: str = "ped") -> Replace:
    """``WALK_civi`` | ``ped/WALK_civi`` | ``ped/WALK_civi=mywalk`` | ``WALK_civi=mywalk``; ``ValueError`` if empty."""
    s = item.strip()
    left, sep, right = s.partition("=")
    block, slash, anim = left.strip().rpartition("/")
    if not slash:
        block = default_block
    anim = anim.strip()
    custom = right.strip() if sep else anim
    if not anim or not custom or not block.strip():
        raise ValueError(f"bad replacement {item!r}: use [block/]game_anim[=custom_anim], e.g. ped/WALK_civi=mywalk")
    return Replace(block.strip(), anim, custom)


def lua_str(s: str) -> str:
    """A Lua double-quoted string literal."""
    out = []
    for ch in s:
        o = ord(ch)
        if ch in ('"', "\\"):
            out.append("\\" + ch)
        elif o < 32 or o > 126:
            out.append(f"\\{o:03d}" if o < 256 else "?")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def _plain(s: str) -> str:
    return "".join(c if 32 <= ord(c) < 127 else "?" for c in s)


def client_lua(ifp_file: str, block: str, replaces: list[Replace], anims: list[str]) -> str:
    rows = "\n".join(f"    {{{lua_str(r.block)}, {lua_str(r.anim)}, {lua_str(r.custom)}}}," for r in replaces)
    names = ", ".join("".join(c if 32 <= ord(c) < 127 else "?" for c in a) for a in anims[:8])
    names += ", ..." if len(anims) > 8 else ""
    return f"""-- Generated by satk anim mta. Loads {_plain(ifp_file)} as the animation block {_plain(block)}
-- (animations: {names}).
-- Play one directly: setPedAnimation(localPlayer, {lua_str(block)}, {lua_str(anims[0]) if anims else '"<name>"'})

local IFP_FILE = {lua_str(ifp_file)}
local BLOCK = {lua_str(block)}
-- game block, game animation, animation of BLOCK
local REPLACE = {{
{rows}
}}
local MAX_TRIES = 10

local ifp

local function apply(ped, tries)
    if #REPLACE == 0 or not ifp or not isElement(ped) then
        return
    end
    local pending = false
    for _, r in ipairs(REPLACE) do
        if not engineReplaceAnimation(ped, r[1], r[2], BLOCK, r[3]) then
            pending = true
        end
    end
    -- a game block that is not loaded yet is requested by the first call: try again shortly
    tries = tries or 0
    if pending and tries < MAX_TRIES then
        setTimer(apply, 500, 1, ped, tries + 1)
    elseif pending then
        outputDebugString("satk: engineReplaceAnimation failed for " .. getElementType(ped), 2)
    end
end

local function applyAll()
    for _, kind in ipairs({{"player", "ped"}}) do
        for _, ped in ipairs(getElementsByType(kind, root, true)) do
            apply(ped)
        end
    end
end

addEventHandler("onClientResourceStart", resourceRoot, function()
    ifp = engineLoadIFP(IFP_FILE, BLOCK)
    if not ifp then
        outputDebugString("satk: engineLoadIFP failed for " .. IFP_FILE .. " (block " .. BLOCK .. ")", 1)
        return
    end
    applyAll()
end)

addEventHandler("onClientElementStreamIn", root, function()
    local kind = getElementType(source)
    if kind == "player" or kind == "ped" then
        apply(source)
    end
end)

addEventHandler("onClientResourceStop", resourceRoot, function()
    for _, kind in ipairs({{"player", "ped"}}) do
        for _, ped in ipairs(getElementsByType(kind, root, true)) do
            for _, r in ipairs(REPLACE) do
                engineRestoreAnimation(ped, r[1], r[2])
            end
        end
    end
end)
"""


def meta_xml(name: str, ifp_file: str, description: str) -> str:
    from xml.sax.saxutils import quoteattr

    return (f"<meta>\n    <info author=\"satk\" type=\"script\" name={quoteattr(name)} description={quoteattr(description)} />\n"
            f"    <script src=\"client.lua\" type=\"client\" />\n    <file src={quoteattr(ifp_file)} />\n</meta>\n")
