"""satk.ingame.resource: Lua literals, the generated content resource, the logic copy."""

from __future__ import annotations

import xml.etree.ElementTree as ET

import pytest

from satk.core import paths
from satk.core.errors import SatkError
from satk.ingame import modset as MS
from satk.ingame import resource as R


def test_lua_literals():
    assert R.lua(None) == "nil" and R.lua(True) == "true" and R.lua(3) == "3" and R.lua(0.25) == "0.25"
    assert R.lua('a"b\\c\n') == '"a\\"b\\\\c\\010"'
    assert R.lua("ü") == '"\\195\\188"'
    assert R.lua([1, "x", [2]]) == '{1, "x", {2}}'
    d = {"b": 1, "a": None, "end": 2, "x y": 3, "ok": False}
    assert R.lua(d) == '{b = 1, ["end"] = 2, ok = false, ["x y"] = 3}'
    with pytest.raises(SatkError):
        R.lua(float("nan"))
    with pytest.raises(SatkError):
        R.lua(object())


def _specs(root, vanilla, **files):
    root.mkdir(parents=True, exist_ok=True)
    for name, data in files.items():
        (root / name).write_bytes(data)
    return MS.scan([str(root)], vanilla=vanilla)[0]


def test_build_content_writes_only_changes(satk_home, tmp_path, vanilla):
    res = paths.work("mta", "server", "mods", "deathmatch", "resources")
    mod = tmp_path / "mod"
    specs = _specs(mod, vanilla, **{"premier.dff": b"dff1", "premier.txd": b"txd1"})
    a = R.build_content(res, specs, label="premier")
    assert a["changed"] == ["m/premier.dff", "m/premier.txd", "manifest.lua", "meta.xml"] and a["removed"] == []
    dst = res / R.CONTENT
    assert (dst / "m" / "premier.dff").read_bytes() == b"dff1"
    meta = ET.parse(dst / "meta.xml").getroot()
    assert [f.get("src") for f in meta.findall("file")] == ["m/premier.dff", "m/premier.txd"]
    assert meta.find("script").get("src") == "manifest.lua" and meta.find("export").get("function") == "manifest"
    lua = (dst / "manifest.lua").read_text(encoding="utf-8")
    assert lua.startswith("-- generated by satk ingame") and f'rev = "{a["rev"]}"' in lua and "function manifest()" in lua
    m = a["manifest"]
    assert m["models"][0]["files"] == {"dff": "m/premier.dff", "txd": "m/premier.txd"} and "runway" in m["geom"]
    b = R.build_content(res, specs, label="premier")
    assert b["changed"] == [] and b["rev"] == a["rev"]
    (mod / "premier.txd").write_bytes(b"txd2")
    c = R.build_content(res, MS.scan([str(mod)], vanilla=vanilla)[0], label="premier")
    assert c["changed"] == ["m/premier.txd", "manifest.lua"] and c["rev"] != a["rev"]
    (mod / "premier.txd").unlink()
    d = R.build_content(res, MS.scan([str(mod)], vanilla=vanilla)[0], label="premier")
    assert d["removed"] == ["m/premier.txd"] and not (dst / "m" / "premier.txd").exists()
    e = R.build_content(res, [], label="vanilla")
    assert e["removed"] == ["m/premier.dff"] and e["manifest"]["models"] == []


def test_rev_depends_on_the_label_and_files(satk_home, tmp_path, vanilla):
    specs = _specs(tmp_path / "mod", vanilla, **{"premier.dff": b"x"})
    blobs, per = R.content_files(specs)
    r1 = R.manifest(specs, per, blobs, label="a")["rev"]
    assert R.manifest(specs, per, blobs, label="a")["rev"] == r1
    assert R.manifest(specs, per, blobs, label="b")["rev"] != r1
    assert R.manifest(specs, per, {"m/premier.dff": b"y"}, label="a")["rev"] != r1


def test_install_logic(satk_home):
    res = paths.work("mta", "server", "mods", "deathmatch", "resources")
    a = R.install_logic(res)
    assert sorted(a["changed"]) == ["checks.lua", "client.lua", "meta.xml", "server.lua", "shared.lua"]
    assert (res / R.LOGIC / "meta.xml").read_bytes() == (R.logic_source() / "meta.xml").read_bytes()
    b = R.install_logic(res)
    assert b["changed"] == [] and b["sha"] == a["sha"]
    (res / R.LOGIC / "server.lua").write_bytes(b"-- edited\n")
    assert R.install_logic(res)["changed"] == ["server.lua"]
