"""``satk data get|patch|explain``: read, change and explain records of the game's data files.

* ``get``: one record with every field, its value and unit (``handling``, ``carcols``, ``peds``, ``weapon``);
* ``patch``: new values for ``handling.cfg`` or ``weapon.dat`` fields, written as a Mod Loader folder with only
  the changed lines (readme lines, merged by Mod Loader), an MTA Lua snippet, or a full patched copy of the file;
* ``explain``: what a field (or a flag bit) means, its unit and range.

Records are read from the profile root (read-only); outputs go to ``<work>/out/addon/<name>/``.
Stdlib only.
"""

from __future__ import annotations

import difflib
import os
import re
from pathlib import Path

from ..core.envelope import clamp_limit, obj, table
from ..core.errors import SatkError
from ..core.paths import atomic_write, cfg, ensure_writable, jpath
from . import fields as F
from . import handling as H
from . import weapon as W
from .game import GameData

__all__ = ["get", "patch", "explain", "resolve_handling", "resolve_weapon", "readme_header", "out_dir"]

_KIND_PREFIX = {"bike", "boat", "flying", "gun", "melee", "aim", "car", "peds", "pedstats"}


def out_dir(name: str) -> Path:
    """``<work>/out/addon/<name>`` (a plain folder name; paths are refused)."""
    if not re.fullmatch(r"[A-Za-z0-9_.-]{1,64}", name) or set(name) == {"."}:
        raise SatkError("BAD_PARAMS", f"bad output name {name!r}", hint="use letters, digits, '_', '-' and '.'")
    return ensure_writable(Path(os.path.abspath(cfg().paths.work)) / "out" / "addon" / name)


def readme_header(title: str) -> list[str]:
    """Comment lines that start a generated Mod Loader readme (``#`` lines are never read as data)."""
    return [f"# {title}", "# Generated by satk. Mod Loader reads the data lines of this file (its readme feature);",
            "# lines starting with # are comments.", ""]


def _split_kind(name: str, allowed: tuple[str, ...]) -> tuple[str | None, str]:
    head, dot, rest = name.partition(".")
    if dot and head.lower() in _KIND_PREFIX and head.lower() in allowed:
        return head.lower(), rest
    return None, name


# --------------------------------------------------------------------------- key resolution


def resolve_handling(gd: GameData, key: str) -> tuple[str, list]:
    """Handling id and the models using it from ``handling:ID``, ``model:411``, ``411``, a model or handling name."""
    rel, hf = gd.handling
    k = key.strip()
    if k.lower().startswith("handling:"):
        hid = k.split(":", 1)[1]
    elif k.lower().startswith("model:") or re.fullmatch(r"\d+", k) or k.lower() in gd.base.by_name:
        m = gd.model(k)
        if m.sec != "cars" or not m.handling:
            raise SatkError("BAD_PARAMS", f"model:{m.id} {m.name} is not a vehicle",
                            hint="give a vehicle model or a handling id")
        hid = m.handling
    else:
        hid = k
    rec = hf.get(hid)
    if rec is None:
        ids = hf.ids()
        close = difflib.get_close_matches(hid.upper(), [i.upper() for i in ids], n=3, cutoff=0.6)
        close += difflib.get_close_matches(hid.lower(), [n for n, m in gd.base.by_name.items() if m.sec == "cars"],
                                           n=3, cutoff=0.7)
        raise SatkError("NOT_FOUND", f"no handling record {hid!r} in {rel}", hint="satk data get handling infernus",
                        did_you_mean=close)
    return rec.hid, gd.models_of_handling(rec.hid)


def resolve_weapon(gd: GameData, key: str) -> tuple[str, list[W.WRec]]:
    """``(label, lines)`` for ``PISTOL``, ``weapon:22``, ``22``, ``model:346``, ``colt45`` or ``aim:colt45``."""
    _rel, wf = gd.weapons
    k = key.strip()
    if k.lower().startswith("aim:"):
        r = wf.aim(k[4:])
        if r is None:
            raise SatkError("NOT_FOUND", f"no aim line for anim group {k[4:]!r}",
                            did_you_mean=[f"aim:{x[1].lower()}" for x in wf.recs if x[0] == "aim"][:5])
        return f"aim:{r.name}", [r]
    name = None
    if k.lower().startswith("weapon:") and not k[7:].strip().isdigit():
        k = k[7:].strip()
    if k.lower().startswith("weapon:") or (re.fullmatch(r"\d+", k) and int(k) < 100):
        wid = int(k.split(":", 1)[-1])
        name = next((n for n, i in F.table("weapon")["types"].items() if i == wid), None)
        if name is None:
            raise SatkError("NOT_FOUND", f"no weapon type {wid}", hint="weapon ids are 0-46 (satk data explain weapon)")
    elif wf.by_type(k):
        name = k.upper()
    else:
        try:
            m = gd.model(k, "weapon")
        except SatkError:
            close = difflib.get_close_matches(k.upper(), wf.types(), n=3, cutoff=0.6)
            raise SatkError("NOT_FOUND", f"no weapon type or weapon model {key!r}",
                            hint="satk data get weapon PISTOL", did_you_mean=close) from None
        hits = sorted({r.name.upper() for r in wf.recs.values() if r.kind != "aim"
                       and m.id in (r.values.get("model1"), r.values.get("model2"))})
        if not hits:
            raise SatkError("NOT_FOUND", f"no weapon.dat line uses model:{m.id} {m.name}")
        if len(hits) > 1:
            raise SatkError("AMBIGUOUS", f"model:{m.id} {m.name} is used by {', '.join(hits)}",
                            hint=f"satk data get weapon {hits[0]}", did_you_mean=hits)
        name = hits[0]
    recs = wf.by_type(name)
    if not recs:
        raise SatkError("NOT_FOUND", f"weapon type {name} has no line in weapon.dat")
    return name, recs


# --------------------------------------------------------------------------- get


def _num(v):
    if isinstance(v, float):
        return round(v, 6)
    return v


def _rows_handling(rec: H.HRec, wanted: set[tuple[str, str]] | None) -> list[list]:
    rows = []
    for f in H.field_table(rec.kind):
        if wanted is not None and (rec.kind, f["key"]) not in wanted:
            continue
        v = rec.values[f["key"]]
        shown = rec.token(f["key"]) if f["type"] == "x" else _num(v)
        label = f["name"] if rec.kind == "car" else f"{rec.kind}.{f['name']}"
        row = [label, shown, H.value_note(rec.kind, f, v)]
        if wanted is not None:
            row.append(f["desc"])
        rows.append(row)
    return rows


def _wanted(file: str, names: list[str] | None, present: tuple[str, ...]) -> set[tuple[str, str]] | None:
    if not names:
        return None
    out = set()
    for n in names:
        kind, bare = _split_kind(n, present)
        if kind is not None:
            k, f = F.find_field(file, bare, kind)
        else:
            k = None
            for kk in present:
                try:
                    k, f = F.find_field(file, bare, kk)
                    break
                except SatkError:
                    continue
            if k is None:
                F.find_field(file, bare)          # raises NOT_FOUND with suggestions
                raise SatkError("NOT_FOUND", f"{n!r} is not a field of the lines this record has",
                                data={"kinds": list(present)})
        out.add((k, f["key"]))
    return out


def get(file: str, key: str, field: list[str] | None = None, profile: str = "vanilla", limit: int = 60,
        cursor: str | None = None) -> dict:
    gd = GameData(profile)
    lim = clamp_limit(limit, default=60)
    off = int(cursor) if cursor and cursor.isdigit() else 0
    extra: dict = {}
    if file == "handling":
        hid, models = resolve_handling(gd, key)
        rel, hf = gd.handling
        recs = hf.kinds_of(hid)
        wanted = _wanted("handling", field, tuple(r.kind for r in recs))
        rows = [row for r in recs for row in _rows_handling(r, wanted)]
        cols = ["field", "value", "unit"] + (["meaning"] if wanted is not None else [])
        extra = {"id": f"handling:{hid}", "file": rel, "lines": [r.line for r in recs],
                 "kinds": [r.kind for r in recs], "models": [f"model:{m.id} {m.name}" for m in models]}
        if not models:
            extra["hint"] = "no vehicles.ide line of this profile uses this handling id"
    elif file == "weapon":
        label, recs = resolve_weapon(gd, key)
        rel, _wf = gd.weapons
        cols, rows = _rows_weapon(recs, field)
        extra = {"id": label if label.startswith("aim:") else f"weapon:{label}", "file": rel,
                 "lines": [r.line for r in recs], "kind": recs[0].kind}
        if recs[0].kind == "gun":
            wid = W.type_id(recs[0].name)
            if wid is not None:
                extra["weapon_id"] = wid
    elif file == "carcols":
        cols, rows, extra = _carcols(gd, key)
    elif file == "peds":
        cols, rows, extra = _peds(gd, key, field)
    else:  # pragma: no cover - Literal in the op
        raise SatkError("BAD_PARAMS", f"unknown data file {file!r}")
    page = rows[off:off + lim]
    env = table(cols, page, total=len(rows), next=str(off + lim) if off + lim < len(rows) else None)
    for k, v in extra.items():
        if v not in (None, [], {}, ""):
            env[k] = v
    return env


def _rows_weapon(recs: list[W.WRec], names: list[str] | None) -> tuple[list[str], list[list]]:
    kind = recs[0].kind
    flist = F.table("weapon")[kind]
    wanted = None
    if names:
        wanted = {F.find_field("weapon", _split_kind(n, (kind,))[1], kind)[1]["key"] for n in names}
    skills = F.table("weapon")["skills"]
    multi = kind == "gun" and len(recs) > 1
    heads = [skills.get(str(r.skill), str(r.skill)) for r in recs] if multi else ["value"]
    cols = ["field"] + heads + ["unit"] + (["meaning"] if wanted else [])
    rows = []
    for f in flist:
        if wanted is not None and f["key"] not in wanted:
            continue
        if f["key"] == "type" or (f["key"] == "skill" and multi) or (kind == "aim" and f["key"] == "anim_group"):
            continue
        vals = []
        for r in recs if multi else recs[:1]:
            if f["key"] not in r.values:
                vals.append("-")
                continue
            v = r.values[f["key"]]
            i = r.first + [x["key"] for x in flist].index(f["key"])
            vals.append(r.tl.get(i) if f["type"] == "x" else _num(v))
        if all(v == "-" for v in vals):
            continue
        ref = next((r.values[f["key"]] for r in recs if f["key"] in r.values), None)
        note = W.value_note(f, ref) if ref is not None else f.get("unit", "")
        if f.get("flags") and multi:
            note = _flag_diff(recs, f, flist)
        row = [f["name"]] + vals + [note]
        if wanted is not None:
            row.append(f["desc"])
        rows.append(row)
    return cols, rows


def _flag_diff(recs: list[W.WRec], f: dict, flist: list[dict]) -> str:
    """Decoded flags of the first line, then what each other skill line adds (+) or lacks (-)."""
    skills = F.table("weapon")["skills"]
    base = F.flag_names("weapon", f["flags"], int(recs[0].values[f["key"]]))
    parts = ["|".join(base) or "none"]
    for r in recs[1:]:
        cur = F.flag_names("weapon", f["flags"], int(r.values[f["key"]]))
        d = [f"+{n}" for n in cur if n not in base] + [f"-{n}" for n in base if n not in cur]
        if d:
            parts.append(f"{skills.get(str(r.skill), r.skill)}: {' '.join(d)}")
    return "; ".join(parts)


def _typed(text: str, typ: str):
    """A file token as a JSON number when it is an int/float field (hex and words stay text)."""
    try:
        if typ == "i":
            return int(text)
        if typ == "f":
            return float(text)
    except ValueError:
        pass
    return text


def _carcols(gd: GameData, key: str) -> tuple[list[str], list[list], dict]:
    m = gd.model(key, "vehicle")
    rel, cc, _text = gd.carcols
    if cc is None:
        raise SatkError("NOT_FOUND", f"profile {gd.profile!r} has no data/carcols.dat")
    entry = cc.cars.get(m.name.lower())
    if entry is None:
        raise SatkError("NOT_FOUND", f"carcols.dat has no colours for {m.name}",
                        hint="the game then uses colour 0 (black) and 0; add a 'car' line")
    pal = cc.palette
    rows = []
    for i, s in enumerate(entry.sets):
        rgb = [pal[c].hex if 0 <= c < len(pal) else "?" for c in s]
        names = [(pal[c].name or "") if 0 <= c < len(pal) else "?" for c in s]
        rows.append([i, ",".join(map(str, s)), " ".join(rgb), ", ".join(names)])
    return ["set", "colors", "rgb", "names"], rows, {"id": f"carcols:{m.name}", "file": rel, "line": entry.line,
                                                      "section": "car4" if entry.four else "car",
                                                      "model": f"model:{m.id}"}


def _peds(gd: GameData, key: str, names: list[str] | None) -> tuple[list[str], list[list], dict]:
    m = gd.model(key, "ped")
    ml = gd.model_line(m)
    t = F.table("peds")
    raw = [tok for tok in ml.text.split("#", 1)[0].replace(",", " ").split()]
    wanted = None
    if names:
        wanted = set()
        for n in names:
            kind, bare = _split_kind(n, ("peds", "pedstats"))
            wanted.add(F.find_field("peds", bare, kind)[1]["key"])
    rows = []
    for f, v in zip(t["peds"], raw):
        if wanted is not None and f["key"] not in wanted:
            continue
        note = f.get("unit", "")
        if f["key"] == "cars_mask":
            try:
                names_ = F.flag_names("peds", "car_groups", int(v, 16))
                note = "|".join(names_) if names_ else "none"
            except ValueError:
                pass
        rows.append([f["name"], _typed(v, f["type"]), note] + ([f["desc"]] if wanted is not None else []))
    stat_name = str(ml.rec.extra.get("stat", ""))
    ps = gd.pedstats
    extra = {"id": f"model:{m.id}", "name": m.name, "file": ml.ide, "line": ml.line}
    if ps is not None:
        hit = next((s for s in ps[1] if s.name.lower() == stat_name.lower()), None)
        if hit is not None:
            extra["pedstats"] = f"{ps[0]}:{hit.line}"
            for f, v in zip(t["pedstats"][1:], hit.values):
                if wanted is not None and f["key"] not in wanted:
                    continue
                rows.append([f"pedstats.{f['key']}", _typed(v, f["type"]), f.get("unit", "")]
                            + ([f["desc"]] if wanted is not None else []))
    return ["field", "value", "unit"] + (["meaning"] if wanted is not None else []), rows, extra


# --------------------------------------------------------------------------- explain


def explain(file: str, field: str | None = None, limit: int = 20, cursor: str | None = None) -> dict:
    t = F.table(file)
    if field is None:
        rows = []
        for kind in F.kinds(file):
            for f in t[kind]:
                name = f.get("name", f["key"])
                label = name if kind in ("car", "gun", "peds") else f"{kind}.{name}"
                rows.append([label, f.get("col", ""), f.get("unit", ""), f["desc"]])
        lim = clamp_limit(limit)
        off = int(cursor) if cursor and cursor.isdigit() else 0
        env = table(["field", "col", "unit", "meaning"], rows[off:off + lim], total=len(rows),
                    next=str(off + lim) if off + lim < len(rows) else None)
        env["hint"] = f"satk data explain {file} <field> (one field with type, range and MTA name)"
        return env
    flag = _flag_bit(file, field)
    if flag is not None:
        return obj(id=f"{file}.{flag[0]}.{flag[1]['name']}", file=file, flags=flag[0], bit=flag[1]["bit"],
                   value=f"0x{1 << flag[1]['bit']:X}", meaning=flag[1].get("desc"))
    allowed = F.kinds(file)
    kind, bare = _split_kind(field, allowed)
    k, f = F.find_field(file, bare, kind)
    env = obj(id=f"{file}.{f.get('name', f['key'])}", file=file, kind=k, key=f["key"], name=f.get("name"),
              col=f.get("col"), type={"f": "float", "i": "int", "x": "hex", "c": "letter", "s": "word"}[f["type"]],
              unit=f.get("unit"), range=f.get("range"), choices=f.get("choices"), meaning=f["desc"],
              aliases=f.get("aliases"))
    if f.get("mta"):
        env["mta"] = f["mta"] if f.get("mta_set", True) else f"{f['mta']} (read-only in MTA)"
        if f.get("mta_scale"):
            env["mta_unit"] = "seconds (file frames / 30)"
    if f.get("flags"):
        env["bits"] = [[f"0x{1 << b['bit']:X}", b["name"], b.get("desc", "")] for b in F.flag_bits(file, f["flags"])]
    if f.get("enum"):
        enum = t.get("enums", {}).get(f["enum"])
        if enum:
            env["values"] = enum
    if file == "handling" and k == "car" and f["key"] in ("drive", "engine"):
        env["values"] = t["enums"][f["key"]]
    if file == "handling":
        env["prefix"] = t["kinds"][k]["prefix"] or "(none)"
    return env


def _flag_bit(file: str, name: str) -> tuple[str, dict] | None:
    t = F.table(file)
    groups = {"handling": ("model_flags", "handling_flags"), "weapon": ("flags",), "peds": ("car_groups",)}[file]
    for g in groups:
        for b in t[g]:
            if b["name"].lower() == name.strip().lower():
                return g, b
    return None


# --------------------------------------------------------------------------- patch


def _parse_sets(sets: list[str]) -> list[tuple[str, str]]:
    out = []
    for s in sets:
        k, eq, v = s.partition("=")
        if not eq or not k.strip() or not v.strip():
            raise SatkError("BAD_PARAMS", f"bad change {s!r}", hint="write field=value, e.g. fMass=1500")
        out.append((k.strip(), v.strip()))
    if not out:
        raise SatkError("BAD_PARAMS", "no changes given", hint="satk data patch handling infernus fMass=1500")
    return out


def _check(file: str, f: dict, text: str):
    if file == "handling":
        return H.check_value(f, text)
    t = text.strip()
    if f["type"] == "x" and t.lower().startswith("0x"):
        t = t[2:]
    from .tokline import parse_typed

    try:
        v = parse_typed(t, f["type"])
    except ValueError as e:
        raise SatkError("BAD_PARAMS", f"{f['name']}: {e}", hint=f"satk data explain weapon {f['name']}") from None
    if "choices" in f and (v.upper() if isinstance(v, str) else v) not in f["choices"]:
        raise SatkError("BAD_PARAMS", f"{f['name']} must be one of {', '.join(map(str, f['choices']))}")
    if isinstance(v, str):
        v = v.upper() if f["key"] in ("fire_type", "base_combo") else v
    return v, None


def patch(file: str, key: str, sets: list[str], target: str = "modloader", profile: str = "vanilla",
          name: str | None = None, skill: str = "all", dry_run: bool = False) -> dict:
    gd = GameData(profile)
    pairs = _parse_sets(sets)
    warn: list[str] = []
    rows: list[list] = []
    old_new: list[tuple] = []          # (old rec, new rec, {key: new value})
    if file == "handling":
        hid, models = resolve_handling(gd, key)
        rel, hf = gd.handling
        recs = {r.kind: r for r in hf.kinds_of(hid)}
        by_kind: dict[str, dict] = {}
        for fname, text in pairs:
            kind, bare = _split_kind(fname, tuple(recs))
            hits = []
            for kk in ([kind] if kind else list(recs)):
                try:
                    hits.append((kk,) + F.find_field("handling", bare, kk))
                except SatkError:
                    pass
            if not hits:
                F.find_field("handling", bare)       # raises NOT_FOUND with suggestions
                raise SatkError("BAD_PARAMS", f"{fname}: {hid} has no line with this field", data={"lines": list(recs)},
                                hint="bike/boat/flying fields need the vehicle's '!', '%' or '$' line")
            if len(hits) > 1:
                raise SatkError("AMBIGUOUS", f"{fname} exists in the {' and '.join(h[0] for h in hits)} lines",
                                hint=f"prefix it: {hits[0][0]}.{bare}",
                                did_you_mean=[f"{h[0]}.{bare}" for h in hits])
            kk, _k, f = hits[0]
            v, w = _check("handling", f, text)
            if w:
                warn.append(w)
            by_kind.setdefault(kk, {})[f["key"]] = (v, text)
        for kk, ch in by_kind.items():
            old = recs[kk]
            new = old.patched(ch)
            old_new.append((old, new, {k2: v for k2, (v, _t) in ch.items()}))
            for k2, (v, _t) in ch.items():
                f = next(x for x in H.field_table(kk) if x["key"] == k2)
                label = f["name"] if kk == "car" else f"{kk}.{f['name']}"
                rows.append([label, old.token(k2), new.token(k2)])
        ident = f"handling:{hid}"
        default_name = f"{hid.lower()}-handling-{target}"
    elif file == "weapon":
        label, recs = resolve_weapon(gd, key)
        rel, wf = gd.weapons
        sel = _skill_filter(recs, skill)
        flist = F.table("weapon")[recs[0].kind]
        changes = {}
        for fname, text in pairs:
            _k, f = F.find_field("weapon", _split_kind(fname, (recs[0].kind,))[1], recs[0].kind)
            if f["key"] in ("type",):
                raise SatkError("BAD_PARAMS", "the weapon type name cannot be patched", hint="patch the other fields")
            v, _w = _check("weapon", f, text)
            changes[f["key"]] = (v, text)
        for r in sel:
            new = r.patched(changes)
            old_new.append((r, new, {k2: v for k2, (v, _t) in changes.items()}))
            for k2 in changes:
                i = r.first + [x["key"] for x in flist].index(k2)
                lab = next(x["name"] for x in flist if x["key"] == k2)
                if r.skill is not None and len(sel) > 1:
                    lab = f"{lab}[{F.table('weapon')['skills'].get(str(r.skill), r.skill)}]"
                rows.append([lab, r.tl.get(i), new.tl.get(i)])
        ident = label if label.startswith("aim:") else f"weapon:{label}"
        default_name = f"{label.replace(':', '-').lower()}-weapon-{target}"
    else:  # pragma: no cover
        raise SatkError("BAD_PARAMS", f"patch supports handling and weapon, not {file!r}")
    folder = out_dir(name or default_name)
    files: list[str] = []
    lua: list[str] = []
    if target == "modloader":
        body, fallback = _modloader(file, old_new, ident)
        if fallback:
            warn.append(f"{fallback}: wrote a full data/{Path(rel).name} copy instead")
            payload = {f"data/{Path(rel).name}": _full(file, gd, old_new)}
        else:
            payload = {f"{(name or default_name)}.txt": body}
    elif target == "full":
        payload = {f"data/{Path(rel).name}": _full(file, gd, old_new)}
    else:
        if file == "handling":
            for old, _new, ch in old_new:
                calls, w = H.mta_calls(old, ch, [(m.id, m.name) for m in models])
                lua += calls
                warn += w
            if not models:
                warn.append(f"NO_MODELS: no vehicle of profile {profile!r} uses handling id {hid}")
        else:
            for old, _new, ch in old_new:
                calls, w = W.mta_calls(old, ch)
                lua += calls
                warn += w
        head = [f"-- {ident}: generated by satk data patch (server side; applies to every vehicle/ped of the model)"]
        if file == "weapon":
            head.append("-- animation frames of weapon.dat are converted to seconds (frames / 30)")
        payload = {f"{file}.lua": "\n".join(head + lua) + "\n"}
    for rel_out, data in sorted(payload.items()):
        dst = folder.joinpath(*rel_out.split("/"))
        if not dry_run:
            atomic_write(dst, data if isinstance(data, bytes) else data.encode("latin-1", errors="replace"))
        files.append(rel_out)
    env = table(["field", "old", "new"], rows, warn=list(dict.fromkeys(warn)))
    env.update({"id": ident, "target": target, "file": rel, "out": jpath(folder), "files": files,
                "old": [o.text for o, _n, _c in old_new], "new": [n.text for _o, n, _c in old_new]})
    if lua:
        env["lua"] = lua[:20]
    if dry_run:
        env["dry_run"] = True
    if target == "modloader" and not dry_run:
        env["hint"] = (f"check: satk mod inspect {jpath(folder)} --profile {profile}; "
                       "install: copy the folder into <game>/modloader/")
    return env


def _skill_filter(recs: list[W.WRec], skill: str) -> list[W.WRec]:
    if recs[0].kind != "gun" or skill == "all":
        return recs
    names = {v: int(k) for k, v in F.table("weapon")["skills"].items()}
    want = int(skill) if skill.isdigit() else names.get(skill.lower())
    if want is None:
        raise SatkError("BAD_PARAMS", f"bad skill {skill!r}", hint="--skill all|poor|std|pro|cop (or 0-3)")
    sel = [r for r in recs if r.skill == want]
    if not sel:
        raise SatkError("NOT_FOUND", f"{recs[0].name} has no skill {skill} line",
                        data={"skills": [r.skill for r in recs]})
    return sel


def _modloader(file: str, old_new: list, ident: str) -> tuple[str, str | None]:
    """Readme text with the changed lines, or ``("", why)`` when Mod Loader would not read one of them."""
    from ..modinspect.traits import HandlingTrait, trim_config_line
    from .add import readme_weapon_ok

    if file == "weapon" and any(o.kind == "aim" for o, _n, _c in old_new):
        return "", "README_UNSUPPORTED: Mod Loader reads no aim ('%') lines from readmes"
    for _o, n, _c in old_new:
        if file == "weapon":
            ok = readme_weapon_ok(n.text)
        else:
            ok = HandlingTrait().readme_rec(trim_config_line(n.text), 0, frozenset()) is not None
        if not ok:
            return "", f"README_FALLBACK: Mod Loader would not read line {n.line} from a readme"
    lines = readme_header(f"{ident}: changed {'handling.cfg' if file == 'handling' else 'weapon.dat'} lines")
    lines += [n.text for _o, n, _c in old_new]
    return "\r\n".join(lines) + "\r\n", None


def _full(file: str, gd: GameData, old_new: list) -> bytes:
    hf = gd.handling[1] if file == "handling" else gd.weapons[1]
    return hf.render({o.line: n.text for o, n, _c in old_new}).encode("latin-1")
