"""``satk blender game-ready``: the satk side of ``make_game_ready`` (M2-08, reports 11 and 22). Stdlib only.

The Blender job (``blender/satk_blender/gameready.py``, contract command ``game_ready``) writes into
the output folder ``work/out/blender/<name>/``:

* ``<name>.dff`` (RW 3.6.0.3, day + night prelight), ``<name>.col`` (COL3, model name = ``<name>``),
  ``lod<name>.dff`` (LOD, a share ``lod`` of the triangles), ``tex/<texture>.png``;
* ``gameready.json`` - the manifest (source, arguments, files, textures, statistics).

:func:`finalize` then (here, in CPython or in Blender's Python for the add-on):

* packs ``tex/*.png`` into ``<name>.txd`` with the texture packer of M2-03 (``satk.texmod``) when it is
  installed; otherwise leaves the PNGs and writes ``TODO-txd.txt`` (warning ``TXD_PENDING``);
* writes ``<name>.ide`` (``objs`` lines for the model and its LOD, ID ``-1`` = to be assigned);
* re-reads the DFF/COL with :mod:`satk.formats` and adds the ``checks`` table (budget, prelight, COL
  name and ±256 m range, name lengths, power-of-two textures).

Budgets come from report 22 §3.1 (vanilla map models, triangles p50 / p90): HD 216 / 1 040, LOD
60 / 262 (LOD ≈ 25 % of HD), draw distance HD 130 / 299, LOD 800 / 1 500.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

from ..core.errors import SatkError
from ..core.paths import atomic_write, cfg, ensure_removable, ensure_writable, jpath

__all__ = ["BUDGETS", "LOD_DRAW", "MANIFEST", "out_dir", "ide_text", "pack_txd", "verify", "finalize"]

#: Triangle budgets of vanilla models by class (report 22 §3.1): ``(p50, p90, max)``.
BUDGETS: dict[str, tuple[int, int, int]] = {
    "map_hd": (216, 1040, 10442),
    "map_lod": (60, 262, 1640),
    "vehicle": (2818, 3343, 5265),
    "ped": (1079, 1274, 2048),
    "weapon": (194, 600, 1254),
}
#: IDE draw distance of a generated LOD model (vanilla LOD p50, report 22 §3.1).
LOD_DRAW = 800
#: Manifest written by the Blender job and completed by :func:`finalize`.
MANIFEST = "gameready.json"
#: RenderWare/IDE limits (report 22 §3.4, report 14).
MAX_VERTS = 65535
MAX_MODEL_NAME = 23
MAX_COL_NAME = 21
MAX_TEX_NAME = 31
COL_RANGE = 256.0
#: Note left next to the PNG textures when no TXD packer is available.
TODO_TXD = "TODO-txd.txt"


def out_dir(name: str, out: str | os.PathLike | None = None) -> Path:
    """Output folder: ``out`` or ``<work>/out/blender/<name>``; must lie under ``work``
    (``PROTECTED_PATH`` otherwise). Creates nothing."""
    wk = Path(os.path.abspath(cfg().paths.work))
    p = ensure_writable(out if out is not None else wk / "out" / "blender" / str(name))  # PROTECTED_PATH
    try:
        p.relative_to(wk)
    except ValueError:
        raise SatkError("PROTECTED_PATH", f"game-ready output is written only under {jpath(wk)}: {jpath(p)}",
                        hint="omit --out (default work/out/blender/<name>) or pick a folder under work/") from None
    return p


def _f(v: float) -> str:
    s = f"{float(v):.2f}".rstrip("0").rstrip(".")
    return s or "0"


def ide_text(name: str, lod: str | None, draw: float, lod_draw: float = LOD_DRAW) -> str:
    """``objs`` section for the model (and its LOD); the TXD has the model's name, IDs are ``-1``."""
    lines = ["# generated by satk blender game-ready: replace -1 with free model IDs;",
             "# link the LOD in the IPL (the HD inst line's lod field = index of the LOD inst line)",
             "objs", f"-1, {name}, {name}, {_f(draw)}, 0"]
    if lod:
        lines.append(f"-1, {lod}, {name}, {_f(lod_draw)}, 0")
    lines.append("end")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- TXD


def _texmod_packer():
    """The TXD writer of M2-03 (``satk.texmod``: DXT encoder, mipmaps, D3D9 natives) when this checkout
    has it, else ``None``. Returns ``pack(textures, txd_path) -> {"formats": {...}, "warn": [...]}``."""
    try:
        from ..texmod.api import build_texture, load_image, prepare
        from ..texmod.txdwrite import txd_chunk
    except (ImportError, AttributeError):  # M2-03 not merged (or its API moved): PNG + TODO
        return None

    def pack(textures: list[dict], txd_path: Path) -> dict:
        from ..formats.txd import parse_txd

        natives, fmts, warn = [], {}, []
        for t in textures:
            img, w = prepare(load_image(Path(t["png"])), t["name"], pot=True)
            b = build_texture(t["name"], img, choice="auto")
            natives.append(b.native)
            fmts[t["name"]] = f"{b.fmt} {b.w}x{b.h} mips {b.levels}"
            warn += list(w) + list(b.warn)
        data = txd_chunk(natives)
        got = sorted(x.name.lower() for x in parse_txd(data).textures)
        if got != sorted(t["name"].lower() for t in textures):
            raise SatkError("INTERNAL", f"the packed TXD holds {got}, expected the {len(textures)} game-ready textures")
        atomic_write(txd_path, data)
        return {"formats": fmts, "warn": warn}

    return pack


def pack_txd(out: Path, name: str, textures: list[dict]) -> dict:
    """``<name>.txd`` from ``tex/*.png`` (``{"txd": path, "txd_formats": {...}}``), or the PNGs plus
    ``TODO-txd.txt`` (``{"png": [...], "todo": path, "warn": ["TXD_PENDING: ..."]}``)."""
    pngs = [t["png"] for t in textures if t.get("png")]
    if not pngs:
        return {}
    packer = _texmod_packer()
    txd = out / f"{name}.txd"
    if packer is not None:
        r = packer([t for t in textures if t.get("png")], txd)
        stale = out / TODO_TXD
        if stale.is_file():
            ensure_removable(stale).unlink()
        return {"txd": jpath(txd), "txd_formats": r["formats"], "warn": r["warn"]}
    lines = [f"{name}: TXD not packed yet - satk texmod (DXT encoder + TXD writer) is not in this checkout.",
             f"The textures are PNG files in {jpath(out / 'tex')}:"]
    lines += [f"  {Path(p).name}  {t.get('w')}x{t.get('h')}{'  alpha' if t.get('alpha') else ''}"
              for p, t in zip(pngs, textures)]
    lines += ["Pack them into " + f"{name}.txd (D3D9, DXT1 / DXT3 with alpha, mipmaps) with",
              f"  satk texture pack {jpath(out / 'tex')} --name {name}",
              "once satk texmod is available, or with Magic.TXD / TXD Workshop.",
              "The DFF already names these textures; the TXD must have the model's name (IDE)."]
    if txd.exists():
        lines.append(f"(an older {txd.name} is still in this folder; it was not rebuilt)")
    atomic_write(out / TODO_TXD, "\n".join(lines) + "\n")
    return {"png": [jpath(p) for p in pngs], "todo": jpath(out / TODO_TXD),
            "warn": [f"TXD_PENDING: {len(pngs)} texture(s) left as PNG in tex/ (no TXD writer in this checkout); "
                     f"see {TODO_TXD}"]}


# --------------------------------------------------------------------------- verification


def _pow2(n: int) -> bool:
    return n > 0 and n & (n - 1) == 0


def _read(p: str | None) -> bytes | None:
    if not p:
        return None
    try:
        return Path(p).read_bytes()
    except OSError:
        return None


def verify(man: dict) -> tuple[list[list], dict]:
    """Re-read the outputs with :mod:`satk.formats`: ``(checks rows [check, status, detail], stats)``.

    ``status`` is ``ok`` / ``warn`` / ``fail``.
    """
    from ..formats.col import iter_col
    from ..formats.dff import F_NIGHT, F_PRELIT, scan_dff
    from ..formats.rw import FormatError

    args = man.get("args") or {}
    files = man.get("files") or {}
    name = man.get("name") or ""
    rows: list[list] = []
    st: dict[str, Any] = {}

    def add(check: str, ok: bool | None, detail: str) -> None:
        rows.append([check, "ok" if ok else ("warn" if ok is None else "fail"), detail])

    dff_texs: list[str] = []
    data = _read(files.get("dff"))
    if data is None:
        add("dff", False, "no DFF written")
    else:
        try:
            info = scan_dff(data)
        except FormatError as e:
            add("dff", False, f"satk.formats cannot read the DFF: {e}")
        else:
            budget = int(args.get("budget") or 0)
            st.update(tris=info.tris, verts=info.verts, materials=len(info.materials))
            add("dff", info.tris <= budget and info.verts <= MAX_VERTS and info.rw_version == 0x36003,
                f"RW 0x{info.rw_version:X}, {info.tris} tris (budget {budget}), {info.verts} verts")
            want = args.get("prelight", "bake") != "none"
            pre = bool(info.flags & F_PRELIT), bool(info.flags & F_NIGHT)
            add("prelight", pre == (want, want) if want else None,
                "day + night" if all(pre) else ("day only" if pre[0] else "none"))
            dff_texs = sorted({m.texture for m in info.materials if m.texture})
            known = {t["name"].lower() for t in man.get("textures") or []}
            missing = [t for t in dff_texs if t.lower() not in known]
            add("tex_refs", not missing,
                f"{len(dff_texs)} texture name(s)" + (f", not exported: {missing}" if missing else ""))
    data = _read(files.get("txd"))
    if data is not None:
        from ..formats.txd import parse_txd

        try:
            txd = parse_txd(data)
        except FormatError as e:
            add("txd", False, f"satk.formats cannot read the TXD: {e}")
        else:
            have = {x.name.lower() for x in txd.textures}
            lack = [t for t in dff_texs if t.lower() not in have]
            add("txd", not lack and all(_pow2(x.w) and _pow2(x.h) for x in txd.textures),
                ", ".join(f"{x.name} {x.d3dfmt} {x.w}x{x.h} mips {x.levels}" for x in txd.textures[:6])
                + (f"; missing: {lack}" if lack else ""))
    elif man.get("textures"):
        add("txd", None, "not packed yet: PNG textures in tex/ (TODO-txd.txt)")
    lod = man.get("lod")
    if lod:
        data = _read(files.get("lod_dff"))
        try:
            info = scan_dff(data) if data else None
        except FormatError:
            info = None
        if info is None:
            add("lod", False, f"{lod}.dff missing or unreadable")
        else:
            st["lod_tris"] = info.tris
            hd = st.get("tris") or 0
            add("lod", info.tris <= max(hd, 1), f"{lod}: {info.tris} tris" + (f" ({info.tris / hd:.0%} of HD)" if hd else ""))
    if args.get("col", "hull") != "none":
        data = _read(files.get("col"))
        try:
            cols = list(iter_col(data, strict=True)) if data else []
        except FormatError as e:
            cols, err = [], str(e)
        else:
            err = "no COL written" if not data else "empty COL"
        if not cols:
            add("col", False, err)
        else:
            c = cols[0]
            st.update(col_faces=c.faces, col_boxes=c.boxes, col_spheres=c.spheres)
            add("col", len(cols) == 1 and c.name == name and c.version == 3,
                f"COL{c.version} {c.name!r}: {c.faces} faces, {c.boxes} boxes, {c.spheres} spheres")
            reach = max((abs(v) for v in c.bbox), default=0.0)
            add("col_range", reach <= COL_RANGE, f"max |coord| {reach:.2f} m (limit {COL_RANGE:.0f})")
    lim = MAX_COL_NAME if args.get("col", "hull") != "none" else MAX_MODEL_NAME
    names = [name] + ([lod] if lod else [])
    add("names", all(len(n) <= MAX_MODEL_NAME for n in names) and len(name) <= lim,
        ", ".join(f"{n} ({len(n)})" for n in names) + f"; limit {lim}" + (f"/{MAX_MODEL_NAME}" if lod else ""))
    texs = man.get("textures") or []
    if texs:
        bad = [t["name"] for t in texs if not (_pow2(int(t.get("w") or 0)) and _pow2(int(t.get("h") or 0)))
               or len(t["name"]) > MAX_TEX_NAME]
        add("textures", not bad, f"{len(texs)} texture(s), "
            + ", ".join(f"{t['name']} {t.get('w')}x{t.get('h')}" for t in texs[:6]) + (f"; bad: {bad}" if bad else ""))
    return rows, st


# --------------------------------------------------------------------------- finalize


def finalize(out: str | os.PathLike) -> dict:
    """Complete a game-ready folder: TXD (or PNG + TODO), IDE, checks; rewrites the manifest.

    Returns ``{"files", "checks", "stats", "warn"}``.
    """
    d = Path(out)
    mp = d / MANIFEST
    try:
        man = json.loads(mp.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        raise SatkError("EXTERNAL_TOOL", f"no game-ready manifest in {jpath(d)}", hint="see the Blender log") from None
    name, lod = man["name"], man.get("lod")
    args = man.get("args") or {}
    files = dict(man.get("files") or {})
    warn: list[str] = []
    tx = pack_txd(d, name, man.get("textures") or [])
    warn += tx.pop("warn", [])
    fmts = tx.pop("txd_formats", None)
    for k in ("txd", "png", "todo"):
        files.pop(k, None)
    files.update(tx)
    if fmts:
        man.setdefault("stats", {})["txd_formats"] = fmts
    ide = d / f"{name}.ide"
    atomic_write(ide, ide_text(name, lod, float(args.get("draw") or 150.0)))
    files["ide"] = jpath(ide)
    man["files"] = files
    checks, st = verify(man)
    man["checks"] = checks
    man.setdefault("stats", {}).update(st)
    files["json"] = jpath(mp)
    atomic_write(mp, json.dumps(man, ensure_ascii=False, indent=1) + "\n")
    bad = [f"{c[0]}: {c[2]}" for c in checks if c[1] == "fail"]
    if bad:
        warn.append("GAME_READY_CHECKS: " + "; ".join(bad))
    return {"files": files, "checks": checks, "stats": man["stats"], "warn": warn}
