"""Text files around a Blender export (SPEC §4.11 ``export``). Owner: WP-10. Stdlib only.

Input: ``export.json`` written by the Blender side (models with their DFF/TXD/COL files and the
placements found in the scene). Output, next to the binaries:

* both targets: ``<name>.ide`` (``objs``/``tobj``/``anim`` lines with the original draw distance,
  flags, times) and ``<name>.ipl`` (``inst`` lines; the IPL quaternion is the conjugate of the world
  rotation, V9; ``interior`` = area + instance flags ``<< 8`` as in the original IPL);
* ``mta-resource``: ``meta.xml`` + ``client.lua`` (``engineRequestModel``, ``engineLoadTXD``,
  ``engineImportTXD``, ``engineLoadDFF``, ``engineReplaceModel``, ``engineLoadCOL``,
  ``engineReplaceCOL``, then ``createObject`` for the placements; MTA object rotation order ``ZXY``);
* ``modloader``: a ``README.txt`` describing where the folder goes (never into the game: SPEC §8).

Never writes into an IMG and only under the export folder (``paths.ensure_writable``).
"""

from __future__ import annotations

import json
import os
import re
from pathlib import Path
from typing import Any

from ..core.errors import SatkError
from ..core.paths import atomic_write, cfg, ensure_writable, jpath

__all__ = ["write_package", "ide_text", "ipl_text", "interior_field", "meta_xml", "client_lua", "export_dir",
           "default_name", "pack_txds", "NAME_RE", "DEFAULT_DRAW"]

#: Fallback base model for engineRequestModel when the original ID is unknown (a plain object).
DEFAULT_OBJECT_BASE = 1337
#: Draw distance written for a model whose IDE definition is unknown (a new object).
DEFAULT_DRAW = 299
_MTA_TYPES = {"cars": "vehicle", "peds": "ped"}
#: Export/resource names (folder and MTA resource name; same rule as the ``export`` contract).
NAME_RE = re.compile(r"[A-Za-z0-9_\-]{1,40}")


def default_name(obj: str) -> str:
    """Export name from an object/model name or SID (``lae2_roads89@lae2_stream0#4`` -> ``lae2_roads89``)."""
    base = obj.split("@")[0].split(".")[0]
    s = "".join(ch if (ch.isascii() and ch.isalnum()) or ch in "_-" else "_" for ch in base).strip("_")[:40]
    return s or "export"


def export_dir(name: str, out: str | os.PathLike | None = None) -> Path:
    """Folder of an export: ``out`` or ``<work>/out/exports/<name>``. Checks the name and that the folder
    is under ``work`` (``BAD_PARAMS``/``PROTECTED_PATH``); creates nothing (the Blender side makes it
    only after the objects are resolved)."""
    if not NAME_RE.fullmatch(str(name)):
        raise SatkError("BAD_PARAMS", f"name: 1-40 characters A-Z a-z 0-9 _ -, got {name!r}",
                        hint="--name my_export (the folder and MTA resource name)")
    wk = Path(os.path.abspath(cfg().paths.work))
    p = ensure_writable(out if out is not None else wk / "out" / "exports" / str(name))  # PROTECTED_PATH
    try:
        p.relative_to(wk)
    except ValueError:
        raise SatkError("PROTECTED_PATH", f"exports are written only under {jpath(wk)}: {jpath(p)}",
                        hint="omit --out (default work/out/exports/<name>) or pick a folder under work/") from None
    return p


def _f(v: float, nd: int = 4) -> str:
    s = f"{float(v):.{nd}f}".rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def ide_text(models: list[dict], first_id: int | None = None) -> str:
    """IDE sections for the exported map objects, with the original definition data (``ide`` of a
    model: draw distance, flags, ``tobj`` times, ``anim`` IFP). Vehicles/peds are skipped: they need
    handling/peds data that a mesh export cannot provide. Unknown definitions get
    :data:`DEFAULT_DRAW` and flags 0."""
    rows: dict[str, list[str]] = {"objs": [], "tobj": [], "anim": []}
    nid = first_id
    for m in models:
        if m.get("sec") in _MTA_TYPES:
            continue
        mid = m.get("id")
        if nid is not None:
            mid, nid = nid, nid + 1
        d = m.get("ide") or {}
        sec = d.get("sec") or m.get("sec") or "objs"
        draw = _f(d["draw"]) if d.get("draw") is not None else str(DEFAULT_DRAW)
        flags = int(d.get("flags") or 0)
        head = f"{mid if mid is not None else -1}, {m['name']}, {m['name']}"
        if sec == "tobj" and d.get("time"):
            rows["tobj"].append(f"{head}, {draw}, {flags}, {int(d['time'][0])}, {int(d['time'][1])}")
        elif sec == "anim" and d.get("anim"):
            rows["anim"].append(f"{head}, {d['anim']}, {draw}, {flags}")
        else:
            rows["objs"].append(f"{head}, {draw}, {flags}")
    lines = ["# generated by satk; IDs: original model IDs, replace them for new objects"]
    for sec in ("objs", "tobj", "anim"):
        if rows[sec] or sec == "objs":
            lines += [sec, *rows[sec], "end"]
    return "\n".join(lines) + "\n"


def interior_field(p: dict) -> int:
    """IPL ``interior`` value of a placement: area (low byte) + instance flags ``<< 8``."""
    return (int(p.get("area") or 0) & 0xFF) | (int(p.get("iflags") or 0) << 8)


def ipl_text(models: list[dict]) -> str:
    """``inst`` section; quaternion as stored in IPL files (= conjugate of the world rotation),
    ``interior`` = area + instance flags (``iflags << 8``) as in the original IPL."""
    lines = ["# generated by satk", "inst"]
    for m in models:
        if m.get("sec") in _MTA_TYPES:
            continue
        mid = m.get("id") if m.get("id") is not None else -1
        for p in m.get("insts", ()):
            x, y, z = p["pos"]
            qx, qy, qz, qw = p["q"]
            lines.append(f"{mid}, {m['name']}, {interior_field(p)}, {_f(x)}, {_f(y)}, {_f(z)}, "
                         f"{_f(-qx, 6)}, {_f(-qy, 6)}, {_f(-qz, 6)}, {_f(qw, 6)}, -1")
    lines.append("end")
    return "\n".join(lines) + "\n"


def meta_xml(name: str, models: list[dict]) -> str:
    files = []
    for m in models:
        for k in ("dff", "txd", "col"):
            if m["files"].get(k):
                files.append(f'    <file src="{Path(m["files"][k]).name}" />')
    return "\n".join([
        "<meta>",
        f'    <info author="satk" type="script" name="{name}" description="generated by satk blender export" />',
        '    <script src="client.lua" type="client" />',
        *files,
        "</meta>",
    ]) + "\n"


def _lua_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def client_lua(name: str, models: list[dict]) -> str:
    out = [
        f"-- {name}: generated by satk from a Blender export. Edit freely.",
        "-- Objects use MTA's default object rotation order ZXY (degrees).",
        "local models = {",
    ]
    for m in models:
        kind = _MTA_TYPES.get(m.get("sec") or "", "object")
        base = m.get("id") if m.get("id") is not None else DEFAULT_OBJECT_BASE
        fs = m["files"]
        fields = [f"name = {_lua_str(m['name'])}", f"kind = {_lua_str(kind)}", f"base = {int(base)}"]
        for k in ("dff", "txd", "col"):
            if fs.get(k):
                fields.append(f"{k} = {_lua_str(Path(fs[k]).name)}")
        insts = []
        if kind == "object":
            for p in m.get("insts", ()):
                x, y, z = p["pos"]
                rx, ry, rz = p.get("rot_zxy_deg", (0.0, 0.0, 0.0))
                insts.append("{" + ", ".join(_f(v) for v in (x, y, z, rx, ry, rz)) + f", {int(p.get('area', 0))}" + "}")
        fields.append("insts = {" + ", ".join(insts) + "}")
        out.append("    { " + ", ".join(fields) + " },")
    out += [
        "}",
        "",
        "local created = {}",
        "",
        'addEventHandler("onClientResourceStart", resourceRoot, function()',
        "    for _, m in ipairs(models) do",
        "        local id = engineRequestModel(m.kind, m.base)",
        "        if not id then",
        '            outputDebugString("satk: engineRequestModel failed for " .. m.name, 1)',
        "        else",
        "            if m.txd then",
        "                local txd = engineLoadTXD(m.txd)",
        "                if txd then engineImportTXD(txd, id) end",
        "            end",
        "            if m.dff then",
        "                local dff = engineLoadDFF(m.dff)",
        "                if dff then engineReplaceModel(dff, id) end",
        "            end",
        "            if m.col then",
        "                local col = engineLoadCOL(m.col)",
        "                if col then engineReplaceCOL(col, id) end",
        "            end",
        "            for _, p in ipairs(m.insts) do",
        "                local o = createObject(id, p[1], p[2], p[3], p[4], p[5], p[6])",
        "                if o then",
        "                    setElementInterior(o, p[7])",
        "                    created[#created + 1] = o",
        "                end",
        "            end",
        "        end",
        "    end",
        "end)",
        "",
    ]
    return "\n".join(out)


def pack_txds(out_dir: str | Path, models: list[dict]) -> list[str]:
    """``<name>.txd`` of every model of ``export.json`` from the PNGs of its own textures (``_tex/<name>/tex``), through
    ``satk.texmod`` like ``kit.export``: DXT1/DXT3 by the class of the IDE section (cars: vehicle, peds: ped, else map);
    shared ``vehicle.txd`` textures stay out. Fills ``files.txd`` and ``sizes`` of each model, removes ``_tex``.
    Models without ``textures`` (an older Blender side wrote the TXD itself) are left alone. Returns warnings."""
    from ..docs.cleanup import remove_tree
    from ..kit.export import pack_own_textures

    d = Path(out_dir)
    warn: list[str] = []
    done = False
    for m in models:
        tex = m.get("textures")
        if tex is None:
            continue
        done = True
        group = {"cars": "vehicle", "peds": "ped"}.get(m.get("sec") or "", "world")
        info = pack_own_textures(tex, d / "_tex" / m["name"], m["name"], group, d, warn)
        m.setdefault("files", {})["txd"] = info["file"]
        m["sizes"] = {k: os.path.getsize(p) for k, p in m["files"].items() if os.path.isfile(p)}
        m["txd"] = {k: v for k, v in info.items() if k != "file"}
        m["textures"] = [{k: v for k, v in t.items() if k != "png"} for t in tex]
    if done and (d / "_tex").is_dir():
        left = remove_tree(ensure_writable(d / "_tex"))
        if left:
            warn.append(f"CLEANUP: could not remove {jpath(d / '_tex')}: {', '.join(left[:3])}")
    return warn


def write_package(out_dir: str | Path, target: str, name: str | None = None) -> dict:
    """Write the text files for ``export.json`` in ``out_dir``; returns ``{"files": [...], "name", "warn"}``.

    ``warn`` has ``IDE_DEFAULTS`` when a map object has no definition data (``ide``) and gets
    :data:`DEFAULT_DRAW`/flags 0 (complete older exports first: ``resolve.fill_export_defs``).
    """
    d = Path(out_dir)
    manifest: dict[str, Any] = json.loads((d / "export.json").read_text(encoding="utf-8"))
    models = manifest.get("models") or []
    name = name or manifest.get("name") or d.name
    written = []
    defaults = [m["name"] for m in models if m.get("sec") not in _MTA_TYPES and (m.get("ide") or {}).get("draw") is None]
    warn = [f"IDE_DEFAULTS: no IDE definition for {', '.join(defaults[:8])}; written with draw {DEFAULT_DRAW}, "
            "flags 0"] if defaults else []

    def w(fn: str, text: str) -> None:
        atomic_write(d / fn, text.replace("\r\n", "\n"))
        written.append(jpath(d / fn))

    map_models = [m for m in models if m.get("sec") not in _MTA_TYPES]
    # vehicles and peds need handling/peds data a mesh export cannot provide (mod.add writes those lines):
    # no empty IDE/IPL fragments for them
    if map_models:
        w(f"{name}.ide", ide_text(models))
    if any(m.get("insts") for m in map_models):
        w(f"{name}.ipl", ipl_text(models))
    if target == "mta-resource":
        w("meta.xml", meta_xml(name, models))
        w("client.lua", client_lua(name, models))
    else:
        w("README.txt", (
            f"{name}: generated by satk\n"
            "Copy this folder into <game>\\modloader\\ of a test copy (never into gta-sa-clean or the\n"
            "original install). The .ide/.ipl use the original model IDs; give new objects free IDs.\n"
            "Textures are DXT1/DXT3 (satk texture pack, class formats).\n"))
    return {"name": name, "files": written, "warn": warn}
