"""Curated engine facts about gta_sa.exe 1.0 US (report 24 §6; owner M2-02).

Our own data (numbers, addresses, names, short Russian notes) — no third-party text. Every fact
carries the trust level of the report (``K`` gta-reversed code, ``2`` a second independent
source, ``E`` gta_sa.exe bytes) and machine checks that ``satk kb build`` re-runs against the
fresh KB and the clean executable:

* ``("func", name, addr)`` — gta-reversed function (hooks.json) at ``addr``;
* ``("global", name, addr)`` — gta-reversed global (``StaticRef``); ``name`` may be unqualified;
* ``("size", type, n)`` / ``("size", type, n, source)`` — asserted struct size;
* ``("limit", name, n)`` — pool/array/store length found in gta-reversed;
* ``("const", name, n)`` / ``("const", name, n, source)`` — evaluated constant or ``#define``;
* ``("u8"|"u16"|"u32", va, n)`` / ``("f32", va, x)`` — value in gta_sa.exe at ``va``;
* ``("section", name, va)`` / ``("section", name, va, nth)`` — PE section start.

A fact is ``verified`` when all its checks pass, ``mismatch`` when one fails and ``unchecked``
when a check could not be run (no exe, source missing).
"""

from __future__ import annotations

__all__ = ["FACTS", "CONFIDENCE"]

#: report-24 letters -> stored confidence
CONFIDENCE = {"K": "code", "K2": "2src", "KE": "exe", "K2E": "exe", "E": "exe"}

# key, topic, title (ru), value, addrs, refs, sources, conf, checks, note
FACTS: list[dict] = [
    {"key": "exe.layout", "title": "Раскладка секций HOODLUM gta_sa.exe",
     "value": ".text 0x401000-0x857000; _rwcseg 0x857000; .rdata 0x858000; .data 0x8A4000 (.bss до 0xC9E000); "
              "_TEXT_HA 0xC9E000; _rwdseg 0xCAF000; слой HOODLUM: .text 0xCB1000, .data 0x1301000, .HOODLUM 0x1556000; "
              "база 0x400000",
     "refs": ["PE header"], "sources": ["exe"], "conf": "E",
     "checks": [("section", ".text", 0x401000), ("section", "_rwcseg", 0x857000), ("section", ".rdata", 0x858000),
                ("section", ".data", 0x8A4000), ("section", "_rwdseg", 0xCAF000), ("section", ".text", 0xCB1000, 1),
                ("section", ".HOODLUM", 0x1556000)]},
    {"key": "pools.initialise", "title": "Пулы создаёт CPools::Initialise",
     "value": "17 пулов; указатели подряд в 0xB74484..0xB744C4", "addrs": [0x550F10, 0xB74484, 0xB744C4],
     "refs": ["game_sa/Pools.cpp"], "sources": ["gta-reversed", "plugin-sdk", "MTA CPoolsSA"], "conf": "K2",
     "checks": [("func", "CPools::Initialise", 0x550F10), ("global", "ms_pPtrNodeSingleLinkPool", 0xB74484),
                ("global", "ms_pPedAttractorPool", 0xB744C4)]},
    {"key": "pools.ped", "title": "Пул педов",
     "value": "140 слотов; элемент 0x7C4 (CCopPed, самый большой ped-класс)", "addrs": [0xB74490, 0x550FF2],
     "refs": ["game_sa/Pools.cpp", "PedPool.h"], "sources": ["gta-reversed", "plugin-sdk", "MTA"], "conf": "K2E",
     "checks": [("global", "ms_pPedPool", 0xB74490), ("limit", "ms_pPedPool", 140), ("u32", 0x550FF2, 140),
                ("size", "CCopPed", 0x7C4)],
     "note": "размер-immediate в 0x550FF2"},
    {"key": "pools.vehicle", "title": "Пул транспорта",
     "value": "110 слотов; элемент 0xA18 (CHeli); push 110 (imm8) в 0x551029", "addrs": [0xB74494, 0x55102A],
     "refs": ["game_sa/Pools.cpp", "VehiclePool.h"], "sources": ["gta-reversed", "MTA"], "conf": "K2",
     "checks": [("global", "ms_pVehiclePool", 0xB74494), ("limit", "ms_pVehiclePool", 110), ("u8", 0x55102A, 110),
                ("size", "CHeli", 0xA18)]},
    {"key": "pools.building_dummy", "title": "Пулы зданий и dummy",
     "value": "Buildings 13 000, Dummys 2 500", "addrs": [0xB74498, 0xB744A0, 0x55105F, 0x5510CF],
     "refs": ["game_sa/Pools.cpp"], "sources": ["gta-reversed", "Sacky Limit Adjuster", "MTA"], "conf": "K2E",
     "checks": [("limit", "ms_pBuildingPool", 13000), ("limit", "ms_pDummyPool", 2500), ("u32", 0x55105F, 13000),
                ("u32", 0x5510CF, 2500), ("global", "ms_pBuildingPool", 0xB74498), ("global", "ms_pDummyPool", 0xB744A0)]},
    {"key": "pools.object", "title": "Пул объектов",
     "value": "350 (MTA upstream поднимает до 1 200); список матриц 900 (MTA: 3 600)", "addrs": [0xB7449C, 0x551097, 0x54F3A1],
     "refs": ["game_sa/Pools.cpp", "MTA Client/game_sa/CGameSA.cpp"], "sources": ["gta-reversed", "MTA"], "conf": "K2E",
     "checks": [("limit", "ms_pObjectPool", 350), ("u32", 0x551097, 350), ("u32", 0x54F3A1, 900),
                ("global", "ms_pObjectPool", 0xB7449C), ("const", "MAX_OBJECTS", 1200, "mta-upstream")]},
    {"key": "pools.colmodel", "title": "Пул ColModel",
     "value": "10 150 (MTA: 12 000; в Neon MAX_COL_MODELS 30 000)", "addrs": [0xB744A4, 0x551107],
     "refs": ["game_sa/Pools.cpp", "MTA Client/sdk/game/Common.h"], "sources": ["gta-reversed", "MTA"], "conf": "K2",
     "checks": [("limit", "ms_pColModelPool", 10150), ("u32", 0x551107, 10150), ("global", "ms_pColModelPool", 0xB744A4),
                ("const", "MAX_COL_MODELS", 30000, "mta-neon")]},
    {"key": "pools.ptrnodes", "title": "Пулы узлов списков",
     "value": "PtrNode Single 70 000, PtrNode Double 3 200, EntryInfoNode 500 (MTA: 90 000 / 74 800 / 72 600)",
     "addrs": [0xB74484, 0xB74488, 0xB7448C, 0x550F46], "refs": ["game_sa/Pools.cpp", "MTA Client/sdk/game/Common.h"],
     "sources": ["gta-reversed", "MTA"], "conf": "K2E",
     "checks": [("limit", "ms_pPtrNodeSingleLinkPool", 70000), ("limit", "ms_pPtrNodeDoubleLinkPool", 3200),
                ("limit", "ms_pEntryInfoNodePool", 500), ("u32", 0x550F46, 70000)]},
    {"key": "pools.tasks_events", "title": "Пулы задач и событий",
     "value": "Task 500, Event 200, PedIntelligence 140 (MTA: Task 5 000, Event 5 000)", "addrs": [0xB744A8, 0xB744AC, 0xB744C0],
     "refs": ["game_sa/Pools.cpp"], "sources": ["gta-reversed", "MTA"], "conf": "K2",
     "checks": [("limit", "ms_pTaskPool", 500), ("limit", "ms_pEventPool", 200), ("limit", "ms_pPedIntelligencePool", 140),
                ("global", "ms_pTaskPool", 0xB744A8), ("global", "ms_pEventPool", 0xB744AC),
                ("global", "ms_pPedIntelligencePool", 0xB744C0)]},
    {"key": "pools.small", "title": "Малые пулы",
     "value": "PointRoute 64, PatrolRoute 32, NodeRoute 64, TaskAllocator 16, PedAttractors 64",
     "addrs": [0xB744B0, 0xB744B4, 0xB744B8, 0xB744BC, 0xB744C4], "refs": ["game_sa/Pools.cpp"],
     "sources": ["gta-reversed", "plugin-sdk", "MTA CLASS_CTaskAllocatorPool"], "conf": "K2",
     "checks": [("limit", "ms_pPointRoutePool", 64), ("limit", "ms_pPatrolRoutePool", 32), ("limit", "ms_pNodeRoutePool", 64),
                ("limit", "ms_pTaskAllocatorPool", 16), ("limit", "ms_pPedAttractorPool", 64),
                ("global", "ms_pTaskAllocatorPool", 0xB744BC)],
     "note": "у gtamods ошибка: TaskAllocator 0xB744CC, верно 0xB744BC"},
    {"key": "pools.handle", "title": "Handle объекта пула (SCM и MTA)",
     "value": "handle = (index << 8) | ref; ref — 7 бит; бит 0x80 в байте флагов = слот пуст",
     "refs": ["game_sa/Core/Pool.h"], "sources": ["gta-reversed", "gtamods Object_pool"], "conf": "K2",
     "checks": [("func", "CPools::GetPedRef", 0x54FF60), ("func", "CPools::GetPed", 0x54FF90)]},
    {"key": "stores.txd", "title": "Стор TXD", "value": "5 000 слотов", "addrs": [0xC8800C],
     "refs": ["game_sa/TxdStore.cpp"], "sources": ["gta-reversed"], "conf": "K",
     "checks": [("global", "CTxdStore::ms_pTxdPool", 0xC8800C)]},
    {"key": "stores.col_ipl", "title": "Сторы COL и IPL",
     "value": "COL-файлов 255, IPL-файлов 256", "addrs": [0x965560, 0x411458, 0x8E3FB0, 0x405F26],
     "refs": ["game_sa/Collision/ColStore.cpp", "game_sa/IplStore.cpp"], "sources": ["gta-reversed", "MTA CLimitsSA"],
     "conf": "K2E", "checks": [("u32", 0x411458, 255), ("u32", 0x405F26, 256)]},
    {"key": "pools.misc", "title": "Прочие пулы",
     "value": "Entry-exits 400, stunt jumps 256, QuadTreeNodes 400", "addrs": [0x96A7D8, 0xA9A888, 0xB745BC, 0x552C3F],
     "refs": ["game_sa/EntryExitManager.cpp", "game_sa/StuntJumpManager.cpp", "game_sa/QuadTreeNode.h"],
     "sources": ["gta-reversed"], "conf": "K2E", "checks": [("u32", 0x552C3F, 400)]},
    {"key": "modelinfo.ptrs", "title": "Таблица modelinfo",
     "value": "CModelInfo::ms_modelInfoPtrs[20000] в 0xA9B0C8 (plugin-sdk читает указатель из операнда 0x40CD67)",
     "addrs": [0xA9B0C8, 0x40CD67], "refs": ["game_sa/Models/ModelInfo.h"], "sources": ["gta-reversed", "plugin-sdk"],
     "conf": "K2", "checks": [("global", "CModelInfo::ms_modelInfoPtrs", 0xA9B0C8), ("limit", "CModelInfo::ms_modelInfoPtrs", 20000)]},
    {"key": "modelinfo.stores", "title": "Ёмкость сторов modelinfo",
     "value": "atomic 14 000, time 169, clump 92, vehicle 212, ped 278, weapon 51, damage-atomic 70, 2dfx 100, lod-atomic 1, "
              "lod-time 1", "refs": ["game_sa/Models/ModelInfo.h"], "sources": ["gta-reversed"], "conf": "K",
     "checks": [("limit", "CModelInfo::ms_atomicModelInfoStore", 14000), ("limit", "CModelInfo::ms_timeModelInfoStore", 169),
                ("limit", "CModelInfo::ms_clumpModelInfoStore", 92), ("limit", "CModelInfo::ms_vehicleModelInfoStore", 212),
                ("limit", "CModelInfo::ms_pedModelInfoStore", 278), ("limit", "CModelInfo::ms_weaponModelInfoStore", 51),
                ("limit", "CModelInfo::ms_damageAtomicModelInfoStore", 70),
                ("limit", "CModelInfo::ms_lodAtomicModelInfoStore", 1), ("limit", "CModelInfo::ms_lodTimeModelInfoStore", 1)]},
    {"key": "streaming.id_ranges", "title": "Диапазоны ID ресурсов стриминга",
     "value": "DFF 0-19999, TXD 20000-24999, COL 25000-25254, IPL 25255-25510, DAT 25511-25574, IFP 25575-25754, "
              "RRR 25755-26229, SCM 26230-26311; всего 26 316", "refs": ["game_sa/Streaming.h"], "sources": ["gta-reversed"],
     "conf": "K", "checks": [("const", "RESOURCE_ID_TXD", 20000), ("const", "RESOURCE_ID_COL", 25000),
                             ("const", "RESOURCE_ID_IPL", 25255), ("const", "RESOURCE_ID_DAT", 25511),
                             ("const", "RESOURCE_ID_IFP", 25575), ("const", "RESOURCE_ID_RRR", 25755),
                             ("const", "RESOURCE_ID_SCM", 26230), ("const", "RESOURCE_ID_TOTAL", 26316)]},
    {"key": "ids.vanilla", "title": "Какие ID занимает ваниль",
     "value": "IDE-определений 14 832, ID 0-18630 без дублей; машины 400-611 (212); слой SA-MP добавляет 11682-19999",
     "refs": ["report 14 §5.2, §5.6"], "sources": ["satk index", "gta-reversed"], "conf": "K2",
     "checks": [("const", "MODEL_VEHICLE_FIRST", 400)]},
    {"key": "streaming.info_array", "title": "Массив CStreamingInfo",
     "value": "26 316 записей по 0x14 байт в CStreaming::ms_aInfoForModel (plugin-sdk читает через операнд 0x408B25)",
     "addrs": [0x8E4CC0, 0x408B25], "refs": ["game_sa/Streaming.h", "game_sa/StreamingInfo.h"],
     "sources": ["gta-reversed", "plugin-sdk"], "conf": "K2",
     "checks": [("global", "CStreaming::ms_aInfoForModel", 0x8E4CC0), ("size", "CStreamingInfo", 0x14)]},
    {"key": "streaming.memory", "title": "Память стриминга",
     "value": "в ванили 50 MiB: статическое 25 600 000 -> stream.ini 'memory' (КБ) -> CStreaming::Init2 пишет 52 428 800",
     "addrs": [0x8A5A80, 0x5BCD50, 0x5BCD78, 0x5B8E64], "refs": ["game_sa/Streaming.cpp", "game_sa/Game.cpp"],
     "sources": ["gta-reversed", "MTA CLimitsSA/CCore", "exe"], "conf": "K2E",
     "checks": [("global", "CStreaming::ms_memoryAvailable", 0x8A5A80), ("u32", 0x8A5A80, 25600000),
                ("u32", 0x5B8E66, 0x8A5A80), ("u32", 0x5B8E6A, 0x3200000), ("func", "CStreaming::Init2", 0x5B8AD0)],
     "note": "mov [0x8A5A80],0x3200000 в 0x5B8E64 перезаписывает stream.ini; MTA глушит все три записи и ставит своё"},
    {"key": "streaming.vehicles", "title": "Число машин в стриминге",
     "value": "статическое 12 -> stream.ini 'vehicles' -> Init2 ставит 22", "addrs": [0x8A5A84, 0x5B8E6E],
     "refs": ["game_sa/Streaming.cpp"], "sources": ["gta-reversed", "MTA SetStreamingVehicles", "exe"], "conf": "K2E",
     "checks": [("u32", 0x8A5A84, 12), ("u32", 0x5B8E70, 0x8A5A84), ("u32", 0x5B8E74, 22)]},
    {"key": "streaming.img_channels", "title": "IMG-архивы и каналы чтения",
     "value": "до 8 IMG-архивов (ms_files), сектор 2 048 байт, 2 канала (ms_channel)",
     "addrs": [0x8E48D8, 0x8E4A60, 0x8E4CB4, 0x8E4CB8], "refs": ["game_sa/Streaming.h"], "sources": ["gta-reversed"],
     "conf": "K", "checks": [("global", "CStreaming::ms_files", 0x8E48D8), ("global", "CStreaming::ms_channel", 0x8E4A60),
                             ("global", "CStreaming::ms_memoryUsedBytes", 0x8E4CB4),
                             ("global", "CStreaming::ms_numModelsRequested", 0x8E4CB8)]},
    {"key": "streaming.rw_instances", "title": "Список RW-инстансов стриминга",
     "value": "ms_rwObjectInstances.Init(12000); MTA upstream -> 30 000; тот же immediate патчат OLA и SilentPatch",
     "addrs": [0x5B8E55], "refs": ["game_sa/Streaming.cpp", "MTA Client/game_sa/CGameSA.cpp"],
     "sources": ["gta-reversed", "MTA", "exe"], "conf": "K2E", "checks": [("u32", 0x5B8E55, 12000)]},
    {"key": "world.bounds", "title": "Границы мира и секторы",
     "value": "WORLD_BOUNDS ±3000; 120x120 секторов по 50 ед. (ms_aSectors); repeat-секторы 16x16; LOD-списки 30x30 "
              "по 200 ед.; MAP_Z_LOW_LIMIT -100", "addrs": [0xB7D0B8, 0xB992B8, 0xB99EB8], "refs": ["game_sa/World.h"],
     "sources": ["gta-reversed"], "conf": "K",
     "checks": [("global", "CWorld::ms_aSectors", 0xB7D0B8), ("global", "CWorld::ms_aRepeatSectors", 0xB992B8),
                ("global", "CWorld::ms_aLodPtrLists", 0xB99EB8)]},
    {"key": "paths.grid", "title": "Сетка путей",
     "value": "8x8 = 64 области по 750 ед. (nodes0..63.dat = DAT ID 0-63); ThePaths в 0x96F050", "addrs": [0x96F050],
     "refs": ["game_sa/PathFind.h"], "sources": ["gta-reversed"], "conf": "K",
     "checks": [("global", "ThePaths", 0x96F050)]},
    {"key": "renderer.lists", "title": "Списки рендера",
     "value": "visible entities 1 000, visible LOD 1 000, super-LOD 50, invisible 150 (в Neon MAX_VISIBLE_* 8 192)",
     "addrs": [0xB75898, 0xB748F8, 0xB74830, 0xB745D8], "refs": ["game_sa/Renderer.h"], "sources": ["gta-reversed"],
     "conf": "K", "checks": [("global", "CRenderer::ms_aVisibleEntityPtrs", 0xB75898),
                             ("global", "CRenderer::ms_aVisibleLodPtrs", 0xB748F8),
                             ("global", "CRenderer::ms_aVisibleSuperLodPtrs", 0xB74830),
                             ("global", "CRenderer::ms_aInVisibleEntityPtrs", 0xB745D8)]},
    {"key": "renderer.lod_scale", "title": "Множители дистанции LOD",
     "value": "ms_lodDistScale 1.2, ms_lowLodDistScale 1.0", "addrs": [0x8CD800, 0x8CD804], "refs": ["game_sa/Renderer.h"],
     "sources": ["gta-reversed", "exe"], "conf": "KE",
     "checks": [("f32", 0x8CD800, 1.2), ("f32", 0x8CD804, 1.0), ("global", "CRenderer::ms_lodDistScale", 0x8CD800)]},
    {"key": "gameplay.arrays", "title": "Массивы геймплея (коронки, пикапы, метки радара)",
     "value": "коронки 64 (aCoronas), пикапы 620 (aPickUps), метки радара 175 (ms_RadarTrace)",
     "addrs": [0xC3E058, 0x9788C0, 0xBA86F0], "refs": ["game_sa/Coronas.h", "game_sa/Pickups.h", "game_sa/Radar.h"],
     "sources": ["gta-reversed", "plugin-sdk", "MTA ARRAY_CORONAS"], "conf": "K2",
     "checks": [("global", "CCoronas::aCoronas", 0xC3E058), ("global", "CPickups::aPickUps", 0x9788C0),
                ("global", "CRadar::ms_RadarTrace", 0xBA86F0)]},
    {"key": "gameplay.arrays2", "title": "Массивы геймплея (генераторы машин, гаражи, пожары, взрывы, снаряды)",
     "value": "car generators 500, гаражи 50, пожары 60 (gFireManager), взрывы 16, снаряды 32",
     "addrs": [0xC27AD0, 0xB71F80, 0xC88950, 0xC89110, 0xC891A8],
     "refs": ["game_sa/TheCarGenerators.h", "game_sa/Garages.h", "game_sa/FireManager.h", "game_sa/Explosion.h",
              "game_sa/ProjectileInfo.h"], "sources": ["gta-reversed", "gtamods"], "conf": "K2",
     "checks": [("global", "gFireManager", 0xB71F80)]},
    {"key": "players", "title": "Игроки",
     "value": "CWorld::Players[2] в 0xB7CD98; CPlayerInfo = 0x190 байт; m_pPed по смещению +0; FindPlayerPed 0x56E210",
     "addrs": [0xB7CD98, 0x56E210], "refs": ["game_sa/World.h", "game_sa/PlayerInfo.h"], "sources": ["gta-reversed", "gtamods"],
     "conf": "K2", "checks": [("global", "CWorld::Players", 0xB7CD98), ("size", "CPlayerInfo", 0x190),
                              ("func", "FindPlayerPed", 0x56E210)]},
    {"key": "scripts.space", "title": "Скриптовая память",
     "value": "ScriptSpace: MAIN 200 000 + MISSION 69 000 байт; глобальная переменная n = 0xA49960 + 4n",
     "addrs": [0xA49960], "refs": ["game_sa/Scripts/TheScripts.h"], "sources": ["gta-reversed", "gtamods"], "conf": "K2",
     "checks": [("global", "CTheScripts::ScriptSpace", 0xA49960)]},
    {"key": "scripts.threads", "title": "Скриптовые потоки",
     "value": "96 CRunningScript (ScriptsArray); миссионных локальных переменных 1 024; ScriptParams[32]",
     "addrs": [0xA8B430, 0xA8B42C, 0xA8B428, 0xA48960, 0xA43C78], "refs": ["game_sa/Scripts/TheScripts.h",
                                                                          "game_sa/Scripts/RunningScript.h"],
     "sources": ["gta-reversed", "gtamods"], "conf": "K2",
     "checks": [("global", "CTheScripts::ScriptsArray", 0xA8B430), ("global", "CTheScripts::pActiveScripts", 0xA8B42C),
                ("global", "CTheScripts::pIdleScripts", 0xA8B428), ("limit", "CTheScripts::ScriptsArray", 96)]},
    {"key": "timer", "title": "Таймер",
     "value": "m_snTimeInMilliseconds 0xB7CB84, ms_fTimeStep 0xB7CB5C, ms_fTimeScale 0xB7CB64, game_FPS 0xB7CB50, "
              "m_FrameCounter 0xB7CB4C; CTimer::Update 0x561B10",
     "addrs": [0xB7CB84, 0xB7CB5C, 0xB7CB64, 0xB7CB50, 0xB7CB4C, 0x561B10], "refs": ["game_sa/Timer.h"],
     "sources": ["gta-reversed", "plugin-sdk", "gtamods"], "conf": "K2",
     "checks": [("global", "CTimer::m_snTimeInMilliseconds", 0xB7CB84), ("global", "CTimer::ms_fTimeStep", 0xB7CB5C),
                ("global", "CTimer::ms_fTimeScale", 0xB7CB64), ("global", "CTimer::game_FPS", 0xB7CB50),
                ("global", "CTimer::m_FrameCounter", 0xB7CB4C), ("func", "CTimer::Update", 0x561B10)]},
    {"key": "clock", "title": "Игровые часы",
     "value": "час 0xB70153, минута 0xB70152, мс на игровую минуту 0xB7015C (.bss, ставится в рантайме, обычно 1 000)",
     "addrs": [0xB70153, 0xB70152, 0xB7015C], "refs": ["game_sa/Clock.h"], "sources": ["gta-reversed", "gtamods"],
     "conf": "K2", "checks": [("global", "CClock::ms_nGameClockHours", 0xB70153),
                              ("global", "CClock::ms_nGameClockMinutes", 0xB70152),
                              ("global", "CClock::ms_nMillisecondsPerGameMinute", 0xB7015C)]},
    {"key": "weather", "title": "Погода и timecyc",
     "value": "23 типа погоды (0-22; 20 = UNDERWATER, 21-22 EXTRACOLOURS); 8 часовых точек timecyc (0, 5, 6, 7, 12, 19, 20, 22 ч)",
     "addrs": [0xC81320, 0xC8131C, 0xC81318], "refs": ["game_sa/Enums/eWeatherType.h", "game_sa/TimeCycle.h",
                                                      "game_sa/Weather.h"],
     "sources": ["gta-reversed", "gtamods"], "conf": "K2",
     "checks": [("global", "CWeather::OldWeatherType", 0xC81320), ("global", "CWeather::NewWeatherType", 0xC8131C),
                ("global", "CWeather::ForcedWeatherType", 0xC81318)],
     "note": "gtamods называет 0xC81320 'Current weather', в коде это OldWeatherType — начало интерполяции"},
    {"key": "handling", "title": "Handling",
     "value": "gHandlingDataMgr: 210 авто + 13 байков + 24 летающих + 12 лодок; tHandlingData = 0xE0; массив машин с +0x14 (0xC2B9DC)",
     "addrs": [0xC2B9C8, 0xC2B9DC], "refs": ["game_sa/cHandlingDataMgr.h", "game_sa/tHandlingData.h"],
     "sources": ["gta-reversed", "gtamods"], "conf": "K2",
     "checks": [("global", "gHandlingDataMgr", 0xC2B9C8), ("size", "tHandlingData", 0xE0)]},
    {"key": "sizes.entities", "title": "Размеры сущностей",
     "value": "CEntity 0x38, CBuilding 0x38, CPhysical 0x138, CObject 0x17C, CPed 0x79C, CPlayerPed 0x7A4, CVehicle 0x5A0, "
              "CAutomobile 0x988, CBike 0x814, CBoat 0x7E8, CTrain 0x6AC, CPlane 0xA04, CHeli 0xA18, CCamera 0xD78, "
              "CColModel 0x30", "refs": ["VALIDATE_SIZE"], "sources": ["gta-reversed", "plugin-sdk"], "conf": "K2",
     "checks": [("size", "CEntity", 0x38), ("size", "CBuilding", 0x38), ("size", "CPhysical", 0x138),
                ("size", "CObject", 0x17C), ("size", "CPed", 0x79C), ("size", "CPlayerPed", 0x7A4),
                ("size", "CVehicle", 0x5A0), ("size", "CAutomobile", 0x988), ("size", "CBike", 0x814),
                ("size", "CBoat", 0x7E8), ("size", "CTrain", 0x6AC), ("size", "CPlane", 0xA04), ("size", "CHeli", 0xA18),
                ("size", "CCamera", 0xD78), ("size", "CColModel", 0x30), ("size", "CPed", 0x79C, "plugin-sdk"),
                ("size", "CVehicle", 0x5A0, "plugin-sdk")]},
    {"key": "singletons", "title": "Ключевые синглтоны",
     "value": "TheCamera 0xB6F028, RwEngineInstance 0xC97B24, IDirect3DDevice9* 0xC97C28, FrontEndMenuManager 0xBA6748, "
              "TheText 0xC1B340, CGame::currArea 0xB72914",
     "addrs": [0xB6F028, 0xC97B24, 0xC97C28, 0xBA6748, 0xC1B340, 0xB72914], "refs": ["gta-reversed", "plugin-sdk common.cpp"],
     "sources": ["gta-reversed", "plugin-sdk", "gtamods"], "conf": "K2",
     "checks": [("global", "TheCamera", 0xB6F028), ("global", "RwEngineInstance", 0xC97B24),
                ("global", "FrontEndMenuManager", 0xBA6748), ("global", "TheText", 0xC1B340),
                ("global", "CGame::currArea", 0xB72914)]},
    {"key": "anims", "title": "Анимации",
     "value": "2 500 иерархий (ms_aAnimations), 180 блоков (ms_aAnimBlocks = TOTAL_IFP)", "addrs": [0xB4EA40, 0xB5D4A0],
     "refs": ["game_sa/Animation/AnimManager.h"], "sources": ["gta-reversed"], "conf": "K",
     "checks": [("global", "CAnimManager::ms_aAnimations", 0xB4EA40), ("global", "CAnimManager::ms_aAnimBlocks", 0xB5D4A0),
                ("limit", "CAnimManager::ms_aAnimations", 2500), ("limit", "CAnimManager::ms_aAnimBlocks", 180)]},
    {"key": "entrypoints", "title": "Главные точки входа",
     "value": "CGame::Initialise -> Init1 -> CFileLoader::LoadLevel -> CStreaming::Init2; кадр: Idle, CGame::Process, "
              "CWorld::Process, CStreaming::Update, CTheScripts::Process, RenderScene, CRenderer::ConstructRenderList",
     "addrs": [0x53BC80, 0x5BF840, 0x5B9030, 0x5B8AD0, 0x53E920, 0x53BEE0, 0x5684A0, 0x40E670, 0x46A000, 0x53DF40, 0x5556E0],
     "refs": ["docs/hooks.json"], "sources": ["gta-reversed"], "conf": "K",
     "checks": [("func", "CGame::Initialise", 0x53BC80), ("func", "CGame::Init1", 0x5BF840),
                ("func", "CFileLoader::LoadLevel", 0x5B9030), ("func", "CStreaming::Init2", 0x5B8AD0),
                ("func", "Idle", 0x53E920), ("func", "CGame::Process", 0x53BEE0), ("func", "CWorld::Process", 0x5684A0),
                ("func", "CStreaming::Update", 0x40E670), ("func", "CTheScripts::Process", 0x46A000),
                ("func", "RenderScene", 0x53DF40), ("func", "CRenderer::ConstructRenderList", 0x5556E0)]},
]


def topic(key: str) -> str:
    return key.split(".", 1)[0]
