"""``satk mta server-check``: let the built MTA server load a resource and report what it says.

A private server tree ``work/mta/check`` gets the server binaries of the MTA fork (``satk engine build --project
server``), a loopback-only config (127.0.0.1, free ports, no ASE/LAN broadcast, no other resources), the stock
``acl.xml`` and a fresh copy of the resource. The server starts headless (``--child-process``, no window, no
client), loads every resource folder, then gets ``start <name>`` on its console; after ``wait`` seconds it gets
``shutdown``. Rows are the server's lines about the resource: load failures (``Couldn't find ...``,
``Loading of resource ... failed``), script errors and warnings of the server scripts, resource-checker
warnings for all scripts. Client scripts are not run (no client): ``satk mta lint`` checks them.
"""

from __future__ import annotations

import os
import shutil
import socket
import struct
import subprocess
import threading
import time
import xml.etree.ElementTree as ET
from pathlib import Path

from ..core.errors import SatkError

__all__ = ["server_check", "check_config", "READY_LINE"]

READY_LINE = "Server started and is ready to accept connections!"
_NO_WINDOW = getattr(subprocess, "CREATE_NO_WINDOW", 0)
_SETTINGS = {
    "servername": "satk server-check (loopback)",
    "serverip": "127.0.0.1",
    "maxplayers": "2",
    "httpserver": "1",
    "httpdownloadurl": "",
    "ase": "0",
    "donotbroadcastlan": "1",
    "minclientversion_auto_update": "0",
    "crash_dump_upload": "0",
    "backup_interval": "0",
    "backup_copies": "0",
    "voice": "0",
    "logfile": "logs/satk-check.log",
    "authfile": "logs/satk-check-auth.log",
    "dbfile": "logs/satk-check-db.log",
    "loadstringfile": "",
    "scriptdebuglogfile": "logs/satk-check-scripts.log",
    "scriptdebugloglevel": "3",
    "password": "",
}


def check_config(template: str, port: int, httpport: int) -> str:
    """``satk-check.conf`` from a shipped ``mtaserver.conf``: loopback, no startup resources, no modules."""
    root = ET.fromstring(template)
    for el in list(root):
        if el.tag in ("resource", "module"):
            root.remove(el)
    values = dict(_SETTINGS, serverport=str(port), httpport=str(httpport))
    for key, val in values.items():
        el = root.find(key)
        if el is None:
            el = ET.SubElement(root, key)
        el.text = val
    ET.indent(root, space="    ")
    return "<!-- generated by satk mta server-check; loopback only -->\n" + ET.tostring(root, encoding="unicode") + "\n"


def _free_port(kind: int) -> int:
    s = socket.socket(socket.AF_INET, kind)
    try:
        s.bind(("127.0.0.1", 0))
        return int(s.getsockname()[1])
    finally:
        s.close()


def _copy_if_changed(src: Path, dst: Path) -> bool:
    from ..core.paths import ensure_writable

    try:
        s, d = src.stat(), dst.stat()
        if s.st_size == d.st_size and int(s.st_mtime) == int(d.st_mtime):
            return False
    except FileNotFoundError:
        pass
    ensure_writable(dst)
    dst.parent.mkdir(parents=True, exist_ok=True)
    tmp = dst.with_name(dst.name + ".tmp")
    shutil.copy2(src, tmp)
    os.replace(tmp, dst)
    return True


def _prepare(res: Path, port: int, httpport: int) -> tuple[Path, Path]:
    from ..core.paths import atomic_write, ensure_removable, ensure_writable, jpath, work
    from ..engine.common import layout

    L = layout()
    srv = L.bin / "server"
    exe = srv / "MTA Server64.exe"
    if not exe.is_file():
        raise SatkError("NOT_READY", f"{jpath(exe)} is not built", hint="satk engine build --project server --platform x64")
    if not (srv / "x64" / "net.dll").is_file():
        raise SatkError("NOT_READY", "Bin/server/x64/net.dll is missing (closed-source net module)",
                        hint="satk engine setup --deps")
    root = work("mta", "check")
    _copy_if_changed(exe, root / exe.name)
    for f in sorted((srv / "x64").glob("*.dll")):
        _copy_if_changed(f, root / "x64" / f.name)
    dm = root / "mods" / "deathmatch"
    sdm = srv / "mods" / "deathmatch"
    fork_dm = L.fork / "Server" / "mods" / "deathmatch"
    tpl = sdm / "mtaserver.conf"
    if not tpl.is_file():
        tpl = fork_dm / "mtaserver.conf"
    if not tpl.is_file():
        raise SatkError("NOT_READY", "no mtaserver.conf in the MTA fork", hint="satk engine build --project server")
    atomic_write(dm / "satk-check.conf", check_config(tpl.read_text(encoding="utf-8-sig", errors="replace"), port,
                                                      httpport))
    for name in ("acl.xml", "vehiclecolors.conf"):
        for base in (sdm, fork_dm):
            if (base / name).is_file():
                _copy_if_changed(base / name, dm / name)
                break
    resources = dm / "resources"
    if resources.exists():
        ensure_removable(resources)
        shutil.rmtree(resources)
    dst = resources / res.name
    ensure_writable(dst / "meta.xml")
    shutil.copytree(res, dst, ignore=shutil.ignore_patterns(".git", "*.old"))
    (dm / "logs").mkdir(parents=True, exist_ok=True)
    return root, dm


def _ready_event() -> int:
    import ctypes

    class _SA(ctypes.Structure):
        _fields_ = [("nLength", ctypes.c_ulong), ("lpSecurityDescriptor", ctypes.c_void_p),
                    ("bInheritHandle", ctypes.c_int)]

    k32 = ctypes.windll.kernel32
    k32.CreateEventW.restype = ctypes.c_void_p
    sa = _SA(ctypes.sizeof(_SA), None, 1)
    h = k32.CreateEventW(ctypes.byref(sa), True, False, None)
    if not h:
        raise SatkError("INTERNAL", "CreateEventW failed")
    return int(h)


def _close(h: int) -> None:
    import ctypes

    ctypes.windll.kernel32.CloseHandle(ctypes.c_void_p(h))


def server_check(res: Path, timeout: float = 60, wait: float = 3) -> dict:
    from ..core.paths import jpath, work
    from .logs import parse_lines

    if os.name != "nt":
        raise SatkError("UNSUPPORTED", "server-check runs the Windows server build", hint="satk mta lint")
    name = res.name
    port, httpport = _free_port(socket.SOCK_DGRAM), _free_port(socket.SOCK_STREAM)
    root, dm = _prepare(res, port, httpport)
    exe = root / "MTA Server64.exe"
    cmd = [str(exe), "--child-process", "--config", "satk-check.conf", "--ip", "127.0.0.1", "--port", str(port),
           "--httpport", str(httpport)]
    h = _ready_event()
    si = subprocess.STARTUPINFO()
    si.lpAttributeList = {"handle_list": [h]}
    lines: list[str] = []
    marks: dict[str, float] = {}
    t0 = time.perf_counter()
    try:
        p = subprocess.Popen(cmd, cwd=str(root), stdin=subprocess.PIPE, stdout=subprocess.PIPE,
                             stderr=subprocess.STDOUT, startupinfo=si, creationflags=_NO_WINDOW)
    except OSError as e:
        _close(h)
        raise SatkError("EXTERNAL_TOOL", f"cannot start the MTA server: {e}") from None

    def reader() -> None:
        assert p.stdout is not None
        for raw in iter(p.stdout.readline, b""):
            s = raw.decode("utf-8", errors="replace").rstrip("\r\n")
            lines.append(s)
            if READY_LINE in s:
                marks.setdefault("ready", time.perf_counter() - t0)
            if f"start: Resource '{name}'" in s:
                marks.setdefault("start", time.perf_counter() - t0)

    th = threading.Thread(target=reader, daemon=True)
    th.start()
    code = None
    start_at = 0
    try:
        assert p.stdin is not None
        p.stdin.write(struct.pack("<Q", h))
        p.stdin.flush()
        deadline = time.perf_counter() + timeout
        while time.perf_counter() < deadline and p.poll() is None and "ready" not in marks:
            time.sleep(0.1)
        if "ready" in marks and p.poll() is None:
            start_at = len(lines)
            p.stdin.write(f"start {name}\n".encode("utf-8"))
            p.stdin.flush()
            t1 = time.perf_counter()
            while time.perf_counter() - t1 < 15 and "start" not in marks and p.poll() is None:
                time.sleep(0.1)
            time.sleep(wait)
        if p.poll() is None:
            try:
                p.stdin.write(b"shutdown\n")
                p.stdin.flush()
            except OSError:
                pass
            try:
                code = p.wait(timeout=30)
            except subprocess.TimeoutExpired:
                subprocess.run(["taskkill", "/T", "/F", "/PID", str(p.pid)], capture_output=True,
                               creationflags=_NO_WINDOW)
                code = p.wait(timeout=30)
        else:
            code = p.returncode
    finally:
        if p.poll() is None:
            subprocess.run(["taskkill", "/T", "/F", "/PID", str(p.pid)], capture_output=True, creationflags=_NO_WINDOW)
        th.join(timeout=10)
        _close(h)
    log = work("mta", "check", "mods", "deathmatch", "logs", "satk-check.out.log")
    try:
        log.write_text("\n".join(lines) + "\n", encoding="utf-8")
    except OSError:
        pass
    if "ready" not in marks:
        raise SatkError("TIMEOUT" if code is None else "EXTERNAL_TOOL",
                        f"the server was not ready within {timeout:g} s (exit {code})", hint=f"see {jpath(log)}",
                        data={"tail": lines[-12:]})
    start_line = next((s for s in lines[start_at:] if f"start: Resource '{name}'" in s), None)
    started = start_line is not None and start_line.rstrip().endswith("started")
    rows: list[list] = []
    for r in parse_lines(lines):
        rel = r.resource == name or name in r.msg
        if not rel and r.level not in ("error", "warning"):
            continue
        if r.msg.startswith(("start: Requested by", "SHUTDOWN:", "Server password")) or r.msg == f"start {name}":
            continue
        row = [r.level, r.resource, r.at, r.msg]
        if row not in rows:
            rows.append(row)
    errors = sum(1 for r in rows if r[0] == "error")
    out = {
        "ok": True,
        "resource": name,
        "started": started,
        "status": (start_line or "").split("] ", 1)[-1] or "no answer to 'start'",
        "errors": errors,
        "warnings": sum(1 for r in rows if r[0] == "warning"),
        "cols": ["level", "res", "at", "msg"],
        "rows": rows[:50],
        "ready_seconds": round(marks["ready"], 2),
        "exit_code": code,
        "log": jpath(log),
        "copy": jpath(dm / "resources" / name),
    }
    if not started:
        out["hint"] = "the resource did not start: the rows show why (satk mta lint names the files and lines)"
    return out
