"""C++ header generator for the patch-site manifest (``satk engine sites-gen``).

Output: ``Shared/sdk/satk/generated/SaeSites.gen.h`` of the fork, deterministic and byte-stable:

* first line: ``// generated by satk engine sites-gen from docs/sae/patch-sites.toml sha256=<hex>; do not edit``
  (the SHA-256 of the TOML with LF line endings);
* everything in ``namespace sae::sites``: ``kManifestSha256``, ``kExeSha256``;
* per group (manifest order) one ``enum class <group> : std::uint16_t`` (dots become underscores, ``COUNT`` last)
  and one ``inline constexpr sae::SiteDef kSites_<group>[]``;
* one ``inline constexpr sae::GroupDef kGroups[]``, ``kGroupCount`` and a ``static_assert`` per group that the
  enum and the array agree.

Stdlib only.
"""

from __future__ import annotations

from pathlib import Path

from .sites_manifest import Group, Manifest, Site, cpp_ident

__all__ = ["HEADER_REL", "MANIFEST_REL", "generate_header", "header_first_line", "header_path", "manifest_path"]

HEADER_REL = "Shared/sdk/satk/generated/SaeSites.gen.h"
MANIFEST_REL = "docs/sae/patch-sites.toml"
_KIND = {"imm8": "Imm8", "imm32": "Imm32", "f32": "F32", "absref": "AbsRef", "code": "Code", "hook": "Hook",
         "data32": "Data32"}
_PHASE = {"ctor": "Ctor", "hooks": "Hooks", "runtime": "Runtime"}
_I = "    "


def header_first_line(sha: str) -> str:
    return f"// generated by satk engine sites-gen from {MANIFEST_REL} sha256={sha}; do not edit"


def _bytes(vals) -> str:
    return "{" + ", ".join(f"0x{v:02X}" for v in vals) + "}" if vals else "{}"


def _site_line(s: Site) -> str:
    gl = len(s.golden)
    alt = [0 if b is None else b for b in s.alt]
    mask = [0 if b is None else 0xFF for b in s.alt]
    base, size, stride = s.array if s.array else (0, 0, 0)
    parts = [
        f'"{s.id}"', f"0x{s.va:X}", str(s.len), f"sae::SiteKind::{_KIND[s.kind]}", f"0x{s.golden_va if gl else 0:X}",
        str(gl), _bytes(list(s.golden)), str(len(s.alt)), _bytes(alt), _bytes(mask),
        f"0x{base:X}", f"0x{size:X}", f"0x{stride:X}", f"0x{s.accept_mask:08X}", f"0x{s.accept_value:08X}",
    ]
    return _I * 2 + "{" + ", ".join(parts) + "},"


def _group_block(g: Group) -> list[str]:
    ci = cpp_ident(g.id)
    head = f"// group {g.id}: report {g.report_id}, phase {g.phase}" + (f", lane {g.lane}" if g.lane else "")
    out = [_I + head, _I + f"enum class {ci} : std::uint16_t", _I + "{"]
    out += [_I * 2 + f"{cpp_ident(s.id)}," for s in g.sites]
    out += [_I * 2 + "COUNT", _I + "};", "", _I + f"inline constexpr sae::SiteDef kSites_{ci}[] = {{"]
    out += [_site_line(s) for s in g.sites]
    out.append(_I + "};")
    return out


def generate_header(man: Manifest) -> str:
    """The full text of ``SaeSites.gen.h`` for ``man`` (LF line endings, final newline)."""
    out = [header_first_line(man.sha256), "#pragma once", "", '#include "../SaePatchPlan.h"', "", "#include <cstddef>",
           "#include <cstdint>", "", "namespace sae::sites", "{",
           _I + f'inline constexpr const char* kManifestSha256 = "{man.sha256}";',
           _I + f'inline constexpr const char* kExeSha256 = "{man.exe_sha256}";', ""]
    for g in man.groups:
        out += _group_block(g)
        out.append("")
    out.append(_I + "inline constexpr sae::GroupDef kGroups[] = {")
    for g in man.groups:
        out.append(_I * 2 + f'{{"{g.id}", {g.report_id}, sae::Phase::{_PHASE[g.phase]}, kSites_{cpp_ident(g.id)}, '
                   f'{len(g.sites)}}},')
    out.append(_I + "};")
    out.append(_I + "inline constexpr std::size_t kGroupCount = sizeof(kGroups) / sizeof(kGroups[0]);")
    out.append("")
    for g in man.groups:
        ci = cpp_ident(g.id)
        out.append(_I + f"static_assert(std::size_t({ci}::COUNT) == sizeof(kSites_{ci}) / sizeof(kSites_{ci}[0]));")
    out.append("}")
    out.append("")
    return "\n".join(out)


def header_path(fork: Path) -> Path:
    return Path(fork) / HEADER_REL


def manifest_path(fork: Path) -> Path:
    return Path(fork) / MANIFEST_REL
