"""``satk engine server-smoke``: start the built x64 server on loopback, wait for ready, stop it.

Card WP-11 item 9 (the full supervisor ``satk engine server`` is WP-15). The run is isolated
and local only:

* config ``Bin\\server\\mods\\deathmatch\\satk-smoke.conf`` generated from the shipped
  ``mtaserver.conf``: ``serverip 127.0.0.1``, ports 22103/22105, ``ase 0``,
  ``donotbroadcastlan 1``, ``minclientversion_auto_update 0``, ``crash_dump_upload 0``,
  no backups, no resources, logs ``logs/satk-smoke*.log``;
* ``--child-process`` protocol (``Server/core/CServerImpl.cpp``): the first 8 bytes on stdin
  are the value of an inheritable event that the server signals when it is ready; stdin stays
  a pipe for console commands (``shutdown``);
* readiness = the event or the line ``Server started and is ready to accept connections!``;
  the sockets the process listens on are read from ``netstat -ano`` (must all be 127.0.0.1).
"""

from __future__ import annotations

import ctypes
import os
import re
import socket
import struct
import subprocess
import threading
import time
import xml.etree.ElementTree as ET

from ..core.errors import SatkError
from ..core.paths import atomic_write, ensure_writable, jpath, work
from .common import Layout, layout, read_json, sha256_file, stamp

__all__ = ["READY_LINE", "smoke_config", "server_smoke", "listening_sockets"]

READY_LINE = "Server started and is ready to accept connections!"
_NO_WINDOW = getattr(subprocess, "CREATE_NO_WINDOW", 0)

_SETTINGS = {
    "servername": "satk smoke (loopback)",
    "serverip": "127.0.0.1",
    "maxplayers": "4",
    "httpserver": "1",
    "httpdownloadurl": "",
    "ase": "0",
    "donotbroadcastlan": "1",
    "minclientversion_auto_update": "0",
    "crash_dump_upload": "0",
    "backup_interval": "0",
    "backup_copies": "0",
    "voice": "0",
    "logfile": "logs/satk-smoke.log",
    "authfile": "logs/satk-smoke-auth.log",
    "dbfile": "logs/satk-smoke-db.log",
    "loadstringfile": "",
    "scriptdebuglogfile": "logs/satk-smoke-scripts.log",
}


def smoke_config(template: str, port: int, httpport: int, password: str) -> str:
    """Rewrite an ``mtaserver.conf`` for a loopback-only run without resources."""
    root = ET.fromstring(template)
    for el in list(root):
        if el.tag in ("resource", "module"):
            root.remove(el)
    values = dict(_SETTINGS, serverport=str(port), httpport=str(httpport), password=password)
    for key, val in values.items():
        el = root.find(key)
        if el is None:
            el = ET.SubElement(root, key)
        el.text = val
    ET.indent(root, space="    ")
    return "<!-- generated by satk engine server-smoke; loopback only, no resources -->\n" + \
        ET.tostring(root, encoding="unicode") + "\n"


def listening_sockets(pid: int) -> list[str]:
    """``["TCP 127.0.0.1:22105", "UDP 127.0.0.1:22103", ...]`` owned by ``pid`` (netstat)."""
    try:
        out = subprocess.run(["netstat", "-ano"], capture_output=True, text=True, timeout=30,
                             creationflags=_NO_WINDOW, errors="replace").stdout
    except (OSError, subprocess.SubprocessError):
        return []
    res = []
    for line in out.splitlines():
        parts = line.split()
        if len(parts) < 4 or parts[0] not in ("TCP", "UDP"):
            continue
        if parts[-1] != str(pid):
            continue
        if parts[0] == "TCP" and (len(parts) < 5 or parts[3] != "LISTENING"):
            continue
        res.append(f"{parts[0]} {parts[1]}")
    return sorted(set(res))


def _port_free(port: int, kind: int) -> bool:
    s = socket.socket(socket.AF_INET, kind)
    try:
        s.bind(("127.0.0.1", port))
        return True
    except OSError:
        return False
    finally:
        s.close()


class _SA(ctypes.Structure):
    _fields_ = [("nLength", ctypes.c_ulong), ("lpSecurityDescriptor", ctypes.c_void_p),
                ("bInheritHandle", ctypes.c_int)]


def _ready_event() -> int:
    k32 = ctypes.windll.kernel32
    k32.CreateEventW.restype = ctypes.c_void_p
    sa = _SA(ctypes.sizeof(_SA), None, 1)
    h = k32.CreateEventW(ctypes.byref(sa), True, False, None)
    if not h:
        raise SatkError("INTERNAL", "CreateEventW failed")
    return int(h)


def _signaled(h: int) -> bool:
    return ctypes.windll.kernel32.WaitForSingleObject(ctypes.c_void_p(h), 0) == 0


def _close(h: int) -> None:
    ctypes.windll.kernel32.CloseHandle(ctypes.c_void_p(h))


def server_smoke(timeout: float = 60, port: int = 22103, httpport: int = 22105, L: Layout | None = None) -> dict:
    """Start ``MTA Server64.exe --child-process`` on 127.0.0.1, wait ready, ``shutdown``."""
    L = L or layout()
    srv = L.bin / "server"
    exe = srv / "MTA Server64.exe"
    if not exe.is_file():
        raise SatkError("NOT_READY", f"{jpath(exe)} not built", hint="satk engine build --project server")
    net = srv / "x64" / "net.dll"
    if not net.is_file():
        raise SatkError("NOT_READY", "Bin/server/x64/net.dll missing (closed-source net module)",
                        hint="satk engine setup --deps")
    lock = {it.get("id"): it for it in (read_json(L.lock, {}) or {}).get("items", []) if isinstance(it, dict)}
    pin = (lock.get("net-x64") or {}).get("sha256")
    if pin and sha256_file(net) != pin:
        raise SatkError("REVISION", "Bin/server/x64/net.dll does not match deps-lock.json",
                        hint="satk engine setup --deps")
    dm = srv / "mods" / "deathmatch"
    tpl_path = dm / "mtaserver.conf"
    if not tpl_path.is_file():
        tpl_path = L.fork / "Server" / "mods" / "deathmatch" / "mtaserver.conf"
    for p, kind in ((port, socket.SOCK_DGRAM), (httpport, socket.SOCK_STREAM)):
        if not _port_free(p, kind):
            raise SatkError("BUSY", f"port {p} on 127.0.0.1 is in use", hint="stop the other server or pass --port")
    password = "satk-" + os.urandom(6).hex()
    conf = dm / "satk-smoke.conf"
    atomic_write(conf, smoke_config(tpl_path.read_text(encoding="utf-8-sig", errors="replace"), port, httpport,
                                    password))
    run_dir = work("engine", "runs", f"{stamp()}-server-smoke")
    log_path = run_dir / "server.out.log"
    ensure_writable(log_path)

    h = _ready_event()
    si = subprocess.STARTUPINFO()
    si.lpAttributeList = {"handle_list": [h]}
    cmd = [str(exe), "--child-process", "--config", conf.name, "--ip", "127.0.0.1",
           "--port", str(port), "--httpport", str(httpport)]
    t0 = time.perf_counter()
    lines: list[str] = []
    ready_at: dict = {}
    try:
        p = subprocess.Popen(cmd, cwd=str(srv), stdin=subprocess.PIPE, stdout=subprocess.PIPE,
                             stderr=subprocess.STDOUT, startupinfo=si, creationflags=_NO_WINDOW)
    except OSError as e:
        _close(h)
        raise SatkError("EXTERNAL_TOOL", f"cannot start the server: {e}") from None

    def reader() -> None:
        assert p.stdout is not None
        for raw in iter(p.stdout.readline, b""):
            s = raw.decode("utf-8", errors="replace").rstrip("\r\n")
            lines.append(s)
            if READY_LINE in s and "line" not in ready_at:
                ready_at["line"] = time.perf_counter() - t0

    th = threading.Thread(target=reader, daemon=True)
    th.start()
    listening: list[str] = []
    clean = False
    code = None
    stop_s = None
    event_ready = False
    try:
        assert p.stdin is not None
        p.stdin.write(struct.pack("<Q", h))
        p.stdin.flush()
        deadline = time.perf_counter() + timeout
        while time.perf_counter() < deadline and p.poll() is None:
            if not event_ready and _signaled(h):
                event_ready = True
                ready_at.setdefault("event", time.perf_counter() - t0)
            if event_ready and "line" in ready_at:
                break
            time.sleep(0.1)
        ready = "line" in ready_at or event_ready
        if ready and p.poll() is None:
            time.sleep(0.5)
            listening = listening_sockets(p.pid)
        if p.poll() is None:
            t1 = time.perf_counter()
            try:
                p.stdin.write(b"shutdown\n")
                p.stdin.flush()
            except OSError:
                pass
            try:
                code = p.wait(timeout=30)
                clean = True
            except subprocess.TimeoutExpired:
                subprocess.run(["taskkill", "/T", "/F", "/PID", str(p.pid)], capture_output=True,
                               creationflags=_NO_WINDOW)
                code = p.wait(timeout=30)
            stop_s = round(time.perf_counter() - t1, 2)
        else:
            code = p.returncode
    finally:
        if p.poll() is None:
            subprocess.run(["taskkill", "/T", "/F", "/PID", str(p.pid)], capture_output=True, creationflags=_NO_WINDOW)
        th.join(timeout=10)
        _close(h)
        log_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    ready = "line" in ready_at
    non_loopback = [s for s in listening if not re.search(r"\s127\.0\.0\.1:\d+$", s)]
    out = {
        "ok": ready and clean and not non_loopback,
        "ready": ready,
        "ready_seconds": round(ready_at["line"], 2) if ready else None,
        "event_signaled": event_ready,
        "ready_line": next((s for s in lines if READY_LINE in s), None),
        "listening": listening,
        "clean_stop": clean,
        "stop_seconds": stop_s,
        "exit_code": code,
        "lines": len(lines),
        "tail": lines[-12:],
        "config": jpath(conf),
        "log": jpath(log_path),
        "cmd": " ".join(f'"{c}"' if " " in c else c for c in cmd),
    }
    if non_loopback:
        out["warn"] = [f"NON_LOOPBACK: listening on {', '.join(non_loopback)}"]
    if not ready:
        raise SatkError("TIMEOUT" if code is None or clean else "EXTERNAL_TOOL",
                        f"server not ready within {timeout:.0f}s (exit {code})", hint=f"see {jpath(log_path)}",
                        data={k: out[k] for k in ("tail", "log", "exit_code")})
    return out
