"""The test server, its state, the client preflight and the bridge to the game.

The server is the private loopback server of the ``game`` target (:mod:`satk.viewer.backends.mta_lua`,
``<work>/mta/server``) with two more startup resources (``satk-testdrive``, ``satk-testdrive-mod``), so
``satk view ... --target game`` keeps working on the same server. :class:`Bridge` talks to the
resources through the ``satk-agent`` rpc (``lua.exec`` on the server or the client, calling the
exports ``td``/``tdc``) and takes frames with the agent's ``capture``. satk never starts the MTA
client here: :func:`write_scripts` writes ``play.cmd`` and the one-time ``admin-setup.ps1`` /
``admin-rollback.ps1`` for the user under ``<work>/mta/ingame``.
"""

from __future__ import annotations

import json
import os
import sys
import time
from pathlib import Path
from typing import Any

from ..core import paths
from ..core.errors import SatkError
from . import resource as R

__all__ = ["PORT", "HTTP_PORT", "ingame_dir", "state_path", "load_state", "save_state", "resources_dir",
           "preflight", "write_scripts", "play_info", "Bridge", "ensure_server", "resource_states",
           "start_resources", "wait_applied", "log_marks"]

PORT, HTTP_PORT = 22040, 22045
_START_ORDER = (R.CONTENT, R.LOGIC)


def ingame_dir() -> Path:
    return paths.work("mta", "ingame")


def state_path() -> Path:
    return ingame_dir() / "state.json"


def load_state() -> dict[str, Any]:
    try:
        d = json.loads(state_path().read_text(encoding="utf-8"))
        return d if isinstance(d, dict) else {}
    except (OSError, ValueError):
        return {}


def save_state(d: dict[str, Any]) -> Path:
    return paths.atomic_write(state_path(), json.dumps(d, indent=1, sort_keys=True, ensure_ascii=False) + "\n")


def resources_dir() -> Path:
    from ..viewer.backends import mta_lua

    return mta_lua.server_root() / "mods" / "deathmatch" / "resources"


# --------------------------------------------------------------------------- client preflight


def preflight() -> dict[str, Any]:
    """Read-only: is the one-time admin setup done, is a game already running, can ``play`` start one."""
    from ..viewer.backends import mta_lua

    pre = mta_lua.client_preflight()
    state = {c[0]: c[1] for c in pre["checks"]}
    setup = [k for k in state if k != "gta_not_running"]
    out: dict[str, Any] = {"ready": bool(pre["ready"]), "setup_done": all(state[k] == "ok" for k in setup),
                           "game_running": state.get("gta_not_running") == "blocker"}
    if pre["blockers"]:
        out["blockers"] = pre["blockers"]
    return out


def _ps1(lines: list[str]) -> bytes:
    # PowerShell 5.1 reads BOM-less UTF-8 as the ANSI code page: write a BOM, CRLF line ends
    return ("﻿" + "\r\n".join(lines) + "\r\n").encode("utf-8")


def write_scripts(port: int) -> dict[str, str]:
    """``play.cmd``, ``admin-setup.ps1`` and ``admin-rollback.ps1`` under ``<work>/mta/ingame`` (for the user)."""
    from ..core.config import REPO_ROOT
    from ..engine.common import layout

    d = ingame_dir()
    game = Path(os.path.abspath(paths.cfg().paths.game))
    bin_ = layout().bin
    exe = bin_ / "Multi Theft Auto.exe"
    setup = [
        "# One-time setup for the MTA fork client of satk on this PC: what the MTA installer would do, nothing more.",
        "# Run it yourself in a 64-bit Windows PowerShell started as administrator. Undo: admin-rollback.ps1.",
        "# Generated by 'satk ingame start'; see the satk page docs/en/mta-agent.md, 'First client run'.",
        "$ErrorActionPreference = 'Stop'",
        f"$game = '{game}'",
        "$users = New-Object Security.Principal.SecurityIdentifier 'S-1-5-32-545'   # BUILTIN\\Users",
        "foreach ($k in 'HKLM:\\SOFTWARE\\WOW6432Node\\Multi Theft Auto: San Andreas All', "
        "'HKLM:\\SOFTWARE\\Multi Theft Auto: San Andreas All') {",
        "    foreach ($sub in \"$k\\Common\", \"$k\\1.7\") {",
        "        if (-not (Test-Path $sub)) { New-Item -Path $sub -Force | Out-Null }",
        "    }",
        "    $acl = Get-Acl $k",
        "    $acl.AddAccessRule((New-Object Security.AccessControl.RegistryAccessRule($users, 'FullControl', "
        "'ContainerInherit', 'None', 'Allow')))",
        "    Set-Acl $k $acl",
        "}",
        "Set-ItemProperty 'HKLM:\\SOFTWARE\\WOW6432Node\\Multi Theft Auto: San Andreas All\\Common' 'GTA:SA Path' $game",
        "$ifeo = 'HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Image File Execution Options\\gta_sa.exe'",
        "if (-not (Test-Path $ifeo)) { New-Item -Path $ifeo -Force | Out-Null }",
        "Set-ItemProperty $ifeo MaxLoaderThreads 1 -Type DWord",
        "New-Item -ItemType Directory -Force \"$env:ProgramData\\MTA San Andreas All\\Common\", "
        "\"$env:ProgramData\\MTA San Andreas All\\1.7\" | Out-Null",
        "icacls \"$env:ProgramData\\MTA San Andreas All\" /grant '*S-1-5-32-545:(OI)(CI)M' | Out-Null",
        "Write-Host \"Done: GTA:SA Path = $game. Now run play.cmd (no administrator needed).\"",
    ]
    rollback = [
        "# Undo admin-setup.ps1 and the traces the MTA fork client leaves after runs.",
        "# Run it in a 64-bit Windows PowerShell started as administrator. Generated by 'satk ingame start'.",
        "$ErrorActionPreference = 'Continue'",
        "Remove-Item -Recurse -Force 'HKLM:\\SOFTWARE\\WOW6432Node\\Multi Theft Auto: San Andreas All', "
        "'HKLM:\\SOFTWARE\\Multi Theft Auto: San Andreas All' -ErrorAction SilentlyContinue",
        "Remove-Item -Recurse -Force 'HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Image File Execution "
        "Options\\gta_sa.exe' -ErrorAction SilentlyContinue",
        "Remove-Item -Recurse -Force \"$env:ProgramData\\MTA San Andreas All\" -ErrorAction SilentlyContinue",
        "Remove-Item -Recurse -Force 'HKCU:\\Software\\Multi Theft Auto: San Andreas All' -ErrorAction SilentlyContinue",
        f"$game = '{game}'",
        f"$bin = '{bin_}'",
        "foreach ($k in 'HKCU:\\Software\\Microsoft\\Windows NT\\CurrentVersion\\AppCompatFlags\\Layers',",
        "               'HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\AppCompatFlags\\Layers') {",
        "    if (Test-Path $k) {",
        "        (Get-Item $k).Property | Where-Object { $_ -like \"$game\\*\" -or $_ -like \"$bin\\*\" } |",
        "            ForEach-Object { Remove-ItemProperty -Path $k -Name $_ }",
        "    }",
        "}",
        "Remove-Item -Recurse -Force \"$bin\\MTA\\dumps\", \"$bin\\MTA\\logs\", \"$bin\\MTA\\config\\coreconfig.xml\" "
        "-ErrorAction SilentlyContinue",
        "Write-Host 'Rollback done.'",
    ]
    env_line = ""
    if (REPO_ROOT / "src" / "satk").is_dir():
        env_line = f'set "PYTHONPATH={REPO_ROOT / "src"}"\r\n'
    play = ("@echo off\r\n"
            "rem Generated by 'satk ingame start': start the MTA fork client and join the satk test server.\r\n"
            "rem Needs the one-time admin-setup.ps1 (next to this file). Without it: connect from a running client\r\n"
            f"rem with F8 and 'connect 127.0.0.1 {port}'.\r\n"
            "setlocal\r\n" + env_line +
            "set \"PYTHONUTF8=1\"\r\n"
            f"\"{sys.executable}\" -X utf8 -m satk ingame play\r\n"
            "if errorlevel 1 pause\r\n")
    out = {}
    for name, data in (("admin-setup.ps1", _ps1(setup)), ("admin-rollback.ps1", _ps1(rollback)),
                       ("play.cmd", play.encode("utf-8"))):
        p = d / name
        try:
            same = p.read_bytes() == data
        except OSError:
            same = False
        if not same:
            paths.atomic_write(p, data)
        out[name.split(".")[0].replace("-", "_")] = paths.jpath(p)
    out["client_exe"] = paths.jpath(exe)
    return out


def play_info(port: int, scripts: dict[str, str] | None = None) -> dict[str, Any]:
    url = f"mtasa://127.0.0.1:{port}"
    out = {"url": url, "command": "satk ingame play", "console": f"connect 127.0.0.1 {port}"}
    if scripts:
        out["file"] = scripts.get("play")
        out["client"] = f"\"{scripts.get('client_exe')}\" {url}"
    return out


# --------------------------------------------------------------------------- bridge


def _lit(v: Any) -> str:
    return R.lua(v if v is not None else {})


class Bridge:
    """``td``/``tdc`` calls and frames through the satk-agent rpc of the ``game`` endpoint."""

    def __init__(self, backend=None):
        if backend is None:
            from ..viewer.backends.mta_lua import MtaLuaBackend

            backend = MtaLuaBackend.from_discovery("game", "game")
        self.b = backend

    def exec(self, code: str, side: str = "server", timeout_ms: int = 8000) -> list:
        r = self.b.call("lua.exec", {"code": code, "side": side, "timeout_ms": timeout_ms})
        err = r.get("error") if isinstance(r, dict) else None
        if err:
            where = f" ({err.get('file')}:{err.get('line')})" if err.get("file") else ""
            raise SatkError("EXTERNAL_TOOL", f"Lua error on the {side}: {err.get('msg')}{where}")
        return list(r.get("values") or []) if isinstance(r, dict) else []

    def _call(self, side: str, fn: str, cmd: str, args: dict | None) -> Any:
        # the client knows only running resources; the server also knows stopped ones (getResourceState)
        code = (f"local r = getResourceFromName({R.lua(R.LOGIC)}) "
                "if not r or (getResourceState and getResourceState(r) ~= 'running') then "
                f"return {{error = {R.lua(R.LOGIC + ' is not running')}, not_running = true}} end "
                f"return call(r, {R.lua(fn)}, {R.lua(cmd)}, {_lit(args)})")
        vals = self.exec(code, side)
        out = vals[0] if vals else None
        if isinstance(out, dict) and out.get("not_running"):
            raise SatkError("NOT_READY", f"{R.LOGIC} is not running on the {side}",
                            hint="satk ingame start" if side == "server" else
                            "the client has not loaded the resources yet: wait, or reconnect")
        if out is None or out is False:
            raise SatkError("NOT_READY", f"{R.LOGIC} did not answer {cmd!r} on the {side}")
        if isinstance(out, dict) and out.get("error"):
            raise SatkError("EXTERNAL_TOOL", f"{R.LOGIC} {cmd}: {out['error']}")
        return out

    def server(self, cmd: str, args: dict | None = None) -> Any:
        return self._call("server", "td", cmd, args)

    def client(self, cmd: str, args: dict | None = None) -> Any:
        return self._call("client", "tdc", cmd, args)

    def hello(self) -> dict:
        self.b._hello = None
        return self.b.call("hello", {})

    def client_joined(self) -> bool:
        return bool((self.hello().get("mta") or {}).get("client"))

    def capture(self, pose: dict | None, prefix: Path, *, w: int, h: int, settle: int | None = None) -> dict:
        params: dict[str, Any] = {"path_prefix": str(prefix).replace("\\", "/"), "w": int(w), "h": int(h)}
        if pose:
            params["pose"] = pose
        if settle is not None:
            params["settle"] = {"max_frames": max(0, min(1200, int(settle)))}
        return self.b.call("capture", params)

    def log_poll(self, since: int = 0, max_items: int = 500) -> dict:
        return self.b.call("log.poll", {"since": int(since), "max": int(max_items)})


# --------------------------------------------------------------------------- server and resources


def ensure_server(port: int, httpport: int, timeout: float) -> tuple[dict, list[str]]:
    """Start the loopback server with the test resources, or reuse the running ``game`` server."""
    from ..viewer.backends import mta_lua

    warn: list[str] = []
    st = mta_lua.status(probe=True)
    if st.get("up"):
        st["reused"] = True
        return st, warn
    p, hp = port, httpport
    if not mta_lua.loopback_port_free(p, udp=True) or not mta_lua.loopback_port_free(hp):
        p, hp = None, None
        warn.append(f"PORT_BUSY: 127.0.0.1:{port}/{httpport} is taken by another program; the server uses free "
                    "ports (see 'connect' in the answer)")
    up = mta_lua.start_server(timeout=timeout, port=p, httpport=hp, extra=list(_START_ORDER))
    return up, warn


def resource_states(bridge: Bridge) -> dict[str, str]:
    names = R.lua([R.CONTENT, R.LOGIC])
    code = (f"local out = {{}} for _, n in ipairs({names}) do local r = getResourceFromName(n) "
            "out[n] = r and getResourceState(r) or 'missing' end return out")
    vals = bridge.exec(code, "server")
    return vals[0] if vals and isinstance(vals[0], dict) else {}


def start_resources(bridge: Bridge, *, logic_changed: bool, content_changed: bool,
                    timeout: float = 20.0) -> dict[str, str]:
    """Make both resources run on the server; restart the ones whose files changed.

    Returns ``{resource: "started" | "restarted" | "running"}``. A content restart goes through
    ``td restart`` so the logic measures the time until the clients have the new models.
    """
    st = resource_states(bridge)
    if any(st.get(n) == "missing" for n in _START_ORDER):
        bridge.exec("refreshResources(false) return true", "server")
        deadline = time.monotonic() + timeout
        while any(st.get(n) == "missing" for n in _START_ORDER):
            if time.monotonic() > deadline:
                raise SatkError("NOT_READY", "the MTA server did not load the test resources",
                                hint="satk ingame logs --source server", data={"states": st})
            time.sleep(0.3)
            st = resource_states(bridge)
    done: dict[str, str] = {}
    for name in _START_ORDER:
        state = st.get(name)
        changed = logic_changed if name == R.LOGIC else content_changed
        if state != "running":
            bridge.exec(f"return startResource(getResourceFromName({R.lua(name)}), true)", "server")
            done[name] = "started"
        elif changed and name == R.CONTENT and st.get(R.LOGIC) == "running":
            bridge.server("restart", {})
            done[name] = "restarted"
        elif changed:
            bridge.exec(f"return restartResource(getResourceFromName({R.lua(name)}))", "server")
            done[name] = "restarted"
        else:
            done[name] = "running"
    deadline = time.monotonic() + timeout
    while True:
        time.sleep(0.3)
        st = resource_states(bridge)
        if all(st.get(n) == "running" for n in _START_ORDER):
            return done
        if time.monotonic() > deadline:
            raise SatkError("TIMEOUT", "the test resources did not start", hint="satk ingame logs --source scripts",
                            data={"states": st})


def wait_applied(bridge: Bridge, rev: str, timeout: float) -> dict[str, Any]:
    """Wait until every ready player reported ``rev``; ``{players, waited_s, timeout?}``."""
    t0 = time.monotonic()
    while True:
        try:
            st = bridge.server("status", {})
        except SatkError as e:
            if e.code != "NOT_READY" or time.monotonic() - t0 > timeout:
                raise
            time.sleep(0.25)  # the logic resource is (re)starting
            continue
        players = [p for p in (st.get("players") or []) if isinstance(p, dict)]
        if players and all(p.get("ready") and p.get("rev") == rev for p in players):
            return {"players": players, "waited_s": round(time.monotonic() - t0, 2)}
        if not players and time.monotonic() - t0 > 2.0:
            return {"players": [], "waited_s": round(time.monotonic() - t0, 2), "no_client": True}
        if time.monotonic() - t0 > timeout:
            return {"players": players, "waited_s": round(time.monotonic() - t0, 2), "timeout": True}
        time.sleep(0.25)


def log_marks() -> dict[str, int]:
    """Current sizes of the server and client log files (``ingame logs --since start`` reads after them)."""
    from .logs import log_files

    out = {}
    for src, p in log_files():
        try:
            out[f"{src}:{p.name}"] = p.stat().st_size
        except OSError:
            out[f"{src}:{p.name}"] = 0
    return out
