"""mta_lua: --conf overrides of the generated server config, template choice, reuse check (no MTA process)."""

from __future__ import annotations

import xml.etree.ElementTree as ET
from pathlib import Path

import pytest

from satk.core.errors import SatkError
from satk.viewer.backends import mta_lua as M

TEMPLATE = """<config>
    <servername>Default MTA Server</servername>
    <serverip>auto</serverip>
    <serverport>22003</serverport>
    <httpport>22005</httpport>
    <ase>1</ase>
    <fpslimit>74</fpslimit>
    <crash_dump_upload>1</crash_dump_upload>
    <resource src="admin" startup="1" protected="0"/>
</config>"""

FORK_TEMPLATE = TEMPLATE.replace("<fpslimit>74</fpslimit>", "<fpslimit>100</fpslimit>\n    <sae_policy>1</sae_policy>")


def _conf(text: str) -> ET.Element:
    return ET.fromstring(text.split("\n", 1)[1])


def test_parse_conf():
    assert M.parse_conf(None) == {} and M.parse_conf([]) == {}
    assert M.parse_conf(["sae_policy=0", " fpslimit = 0 ", "sae_policy=1"]) == {"sae_policy": "1", "fpslimit": "0"}
    assert M.parse_conf({"maxplayers": 8}) == {"maxplayers": "8"}
    for bad in ("nonsense", "=1", "a b=1", "x=" + "y" * 201, "x=a\nb"):
        with pytest.raises(SatkError) as e:
            M.parse_conf([bad])
        assert e.value.code == "BAD_PARAMS"
    for locked in ("serverip", "ASE", "donotbroadcastlan", "httpport", "acl", "password", "crash_dump_upload", "resource"):
        with pytest.raises(SatkError) as e:
            M.parse_conf([f"{locked}=1"])
        assert e.value.code == "BAD_PARAMS" and "fixed by satk" in e.value.msg


def test_server_config_applies_overrides_but_keeps_the_safety_values():
    cfg = M.server_config(FORK_TEMPLATE, 40001, 40002, conf={"sae_policy": "0", "fpslimit": "0",
                                                              "sae_actor_stream_distance": "500",
                                                              "sae_dev_stock_translator": "1"})
    root = _conf(cfg)
    assert root.findtext("sae_policy") == "0" and root.findtext("fpslimit") == "0"
    assert root.findtext("sae_actor_stream_distance") == "500" and root.findtext("sae_dev_stock_translator") == "1"
    assert root.findtext("serverip") == "127.0.0.1" and root.findtext("ase") == "0"
    assert root.findtext("crash_dump_upload") == "0"
    assert root.findtext("donotbroadcastlan") == "1" and [r.get("src") for r in root.findall("resource")] == ["satk-agent"]
    head = cfg.split("\n", 1)[0]
    assert head.startswith("<!-- generated by satk") and "overrides: fpslimit=0, sae_actor_stream_distance=500" in head
    plain = _conf(M.server_config(FORK_TEMPLATE, 40001, 40002))
    assert plain.findtext("fpslimit") == "100" and plain.findtext("sae_policy") == "1"        # the template's own values stay
    with pytest.raises(SatkError):
        M.server_config(TEMPLATE, 1, 2, conf={"ase": "1"})
    hostile = M.server_config(TEMPLATE, 1, 2, conf={"servername": "a --> <b>"})
    assert _conf(hostile).findtext("servername") == "a --> <b>"                                # valid XML, comment intact


@pytest.fixture
def fake_build(satk_home, monkeypatch):
    bin_ = satk_home / "engine" / "mtasa" / "Bin"
    srv = bin_ / "server"
    (srv / "x64").mkdir(parents=True)
    (srv / "mods" / "deathmatch").mkdir(parents=True)
    (srv / "MTA Server64.exe").write_bytes(b"MZ fake")
    for n in ("core.dll", "net.dll", "deathmatch.dll"):
        (srv / "x64" / n).write_bytes(b"MZ " + n.encode())
    monkeypatch.setattr(M, "_engine_bin", lambda: bin_)
    src = satk_home / "engine" / "mtasa" / "Server" / "mods" / "deathmatch"
    src.mkdir(parents=True)
    return {"srv": srv, "bin": srv / "mods" / "deathmatch" / "mtaserver.conf", "src": src / "mtaserver.conf"}


def test_pick_template_prefers_the_fork_source(fake_build):
    srv = fake_build["srv"]
    with pytest.raises(SatkError) as e:
        M.pick_template(srv)
    assert e.value.code == "NOT_READY"
    fake_build["bin"].write_text(TEMPLATE, encoding="utf-8")
    assert M.pick_template(srv) == (fake_build["bin"], "bin", None)
    fake_build["src"].write_text(FORK_TEMPLATE, encoding="utf-8")
    p, kind, note = M.pick_template(srv)
    assert p == fake_build["src"] and kind == "fork-source" and "differs" in note and "stale" in note
    fake_build["bin"].write_text(FORK_TEMPLATE, encoding="utf-8")
    assert M.pick_template(srv)[2] is None                                                     # same: no note
    fake_build["bin"].unlink()
    assert M.pick_template(srv)[1] == "fork-source"


def test_prepare_server_uses_the_source_template_and_the_overrides(fake_build):
    fake_build["bin"].write_text(TEMPLATE, encoding="utf-8")
    fake_build["src"].write_text(FORK_TEMPLATE, encoding="utf-8")
    r = M.prepare_server(40001, 40002, "ab" * 32, conf={"sae_policy": "0"})
    assert r["template"] == "fork-source" and "stale" in r["template_note"] and r["conf"] == {"sae_policy": "0"}
    assert r["template_path"].endswith("Server/mods/deathmatch/mtaserver.conf")
    root = ET.fromstring(Path(r["config"]).read_text(encoding="utf-8").split("\n", 1)[1])
    assert root.findtext("fpslimit") == "100" and root.findtext("sae_policy") == "0"
    fake_build["src"].unlink()
    r = M.prepare_server(40001, 40002, "ab" * 32)
    assert r["template"] == "bin" and "conf" not in r and "template_note" not in r
    assert ET.fromstring(Path(r["config"]).read_text(encoding="utf-8").split("\n", 1)[1]).findtext("fpslimit") == "74"


def test_check_conf_reuse():
    M.check_conf_reuse({"up": True}, None)                                   # nothing asked: any running server is fine
    M.check_conf_reuse({"up": True, "conf": {"a": "1"}}, ["a=1"])
    with pytest.raises(SatkError) as e:
        M.check_conf_reuse({"up": True}, ["sae_policy=0"])
    assert e.value.code == "NOT_READY" and "ingame stop" in e.value.hint and e.value.data["wanted"] == {"sae_policy": "0"}
    with pytest.raises(SatkError):
        M.check_conf_reuse({"up": True, "conf": {"sae_policy": "1"}}, {"sae_policy": "0"})


def test_start_server_refuses_a_conflicting_reuse(satk_home, monkeypatch):
    running = {"up": True, "pid": 1, "conf": {"sae_policy": "1"}}
    monkeypatch.setattr(M, "_discovery", lambda: ({"pid": 1}, {}, "ok"))
    monkeypatch.setattr(M, "status", lambda probe=True: dict(running))
    assert M.start_server(conf=["sae_policy=1"])["reused"] is True
    assert M.start_server()["reused"] is True
    with pytest.raises(SatkError) as e:
        M.start_server(conf=["sae_policy=0"])
    assert e.value.code == "NOT_READY"
    with pytest.raises(SatkError) as e:
        M.start_server(conf=["ase=1"])
    assert e.value.code == "BAD_PARAMS"


def test_cli_up_rejects_cvars_without_the_client_and_locked_conf(satk_home, capsys):
    assert M.main(["up", "--cvar", "vsync=0"]) != 0
    assert "BAD_PARAMS" in capsys.readouterr().out
    assert M.main(["up", "--conf", "ase=1"]) != 0
    assert "fixed by satk" in capsys.readouterr().out
