"""``satk dev gen-docs``: generated agent docs (SPEC §4.13).

* ``docs/agent/tools.md`` -- every MCP tool (description, parameters) and every command without a
  tool of its own (reachable through ``satk_op`` or CLI only), straight from the registry;
* ``docs/agent/schema.md`` -- every ``src/satk/<pkg>/schema.sql`` as tables and columns.

Output is deterministic (sorted, no timestamps), so ``--check`` can tell whether the committed
files match the code. After merging packages that add operations or schemas, re-run it.
"""

from __future__ import annotations

from pathlib import Path

from satk.core.config import REPO_ROOT
from satk.core.registry import GROUPS, OpSpec, all_ops

from .schemadoc import read_schema, schema_files

__all__ = ["DOCS", "render_tools", "render_schema", "generate"]

_HEADER = "<!-- generated by `satk dev gen-docs` from {src}; do not edit by hand -->\n"


def _md(s: str) -> str:
    return s.replace("|", "\\|").replace("\n", " ")


def _default(spec_param) -> str:
    from .help import _json_default

    if spec_param.required:
        return "required"
    return _json_default(spec_param.default if spec_param.has_default else None)


def _tool_block(o: OpSpec) -> list[str]:
    from satk.mcp.adapter import tool_name

    title = tool_name(o) or f"satk {o.cli}"
    lines = [f"### `{title}`", "", f"CLI: `satk {o.cli}`" + ("  ·  long-running (subprocess, progress)"
                                                              if o.long_running else ""), "", _md(o.summary), ""]
    if o.params:
        lines += ["| parameter | type | default | description |", "|---|---|---|---|"]
        for p in o.params:
            lines.append(f"| `{p.name}` | {_md(p.type_label)} | {_md(_default(p))} | {_md(p.help)} |")
        lines.append("")
    if o.examples:
        lines += ["Examples: " + " · ".join(f"`{_md(e)}`" for e in o.examples), ""]
    return lines


def render_tools() -> str:
    from satk.mcp import adapter, generic

    mops = adapter.mcp_ops(None)
    defs = adapter.tool_defs(None)
    lines = [_HEADER.format(src="the operation registry"), "# satk: MCP tools and CLI commands", "",
             f"MCP server `satk` (stdio, `python -m satk.mcp`): **{len(mops)} tools**, tools/list response = "
             f"{adapter.list_bytes(defs)} bytes (budget {adapter.LIST_BUDGET}). Every tool is also a CLI command "
             "with the same parameters (`satk <words>`; positionals = required parameters). Commands without a "
             "tool of their own are reached through `satk_ops(query)` -> `satk_op(op, args)` unless marked CLI only "
             "(`satk help ops`).", "",
             "Server instructions:", "", "> " + adapter.INSTRUCTIONS, "", "## MCP tools", ""]
    cur = None
    for o in mops:
        if o.mcp_group != cur:
            cur = o.mcp_group
            lines += [f"#### group `{cur}`", ""]
        lines += _tool_block(o)
    rest = [o for o in all_ops() if not adapter.tool_name(o)]
    order = {g: i for i, g in enumerate(GROUPS)}
    rest.sort(key=lambda o: (order.get(o.group, 99), o.name))

    def via(o: OpSpec) -> str:
        why = generic.denial(o)
        return f"`satk_op(\"{o.name}\")`" if why is None else f"CLI only ({why[0]})"

    lines += ["## Commands without their own MCP tool", "", "| command | MCP | summary |", "|---|---|---|"]
    lines += [f"| `satk {o.cli}` | {_md(via(o))} | {_md(o.summary)} |" for o in rest]
    lines.append("")
    return "\n".join(lines)


def render_schema() -> str:
    lines = [_HEADER.format(src="src/satk/*/schema.sql"), "# satk: SQLite schemas", "",
             "Read-only SQL over these databases: `index_query(sql, params, db=\"index\"|\"re\"|\"notes\")` "
             "(CLI `satk index query`).", ""]
    for pkg, path in schema_files():
        info = read_schema(pkg, path)
        rel = path.relative_to(REPO_ROOT).as_posix()
        lines += [f"## {pkg}: `{info.db}`", "", f"Source `{rel}`, `PRAGMA user_version = {info.user_version}`.", ""]
        if info.error:
            lines += [f"(schema did not execute: {_md(info.error)})", ""]
        lines += ["| table | kind | columns |", "|---|---|---|"]
        for t in info.tables:
            cols = ", ".join(f"{c}{' ' + typ if typ else ''}{' PK' if pk else ''}" for c, typ, pk in t.columns)
            lines.append(f"| `{t.name}` | {t.kind} | {_md(cols)} |")
        lines.append("")
    return "\n".join(lines)


#: relative path -> renderer
DOCS = {"docs/agent/tools.md": render_tools, "docs/agent/schema.md": render_schema}


def generate(root: Path | None = None, *, check: bool = False) -> dict:
    """Render all docs; write changed ones (or only compare with ``check=True``)."""
    from satk.core.errors import SatkError
    from satk.core.paths import atomic_write, jpath

    base = Path(root) if root is not None else REPO_ROOT
    written, unchanged, stale = [], [], []
    for rel, fn in DOCS.items():
        text = fn()
        target = base / rel
        old = target.read_text(encoding="utf-8") if target.is_file() else None
        if old is not None and old.replace("\r\n", "\n") == text:
            unchanged.append(rel)
            continue
        if check:
            stale.append(rel)
            continue
        atomic_write(target, text.encode("utf-8"))
        written.append(rel)
    if stale:
        raise SatkError("REVISION", f"generated docs are stale: {', '.join(stale)}", hint="satk dev gen-docs",
                        data={"stale": stale, "root": jpath(base)})
    return {"root": jpath(base), "written": written, "unchanged": unchanged, "check": check}
