<#
  satk engine bootstrap (WP-11, SPEC 4.12). Generated by `satk engine setup`; do not edit.

  Sets up {{WORKSPACE}}\engine for a human: offline fork from src\mtasa-neon, build shims,
  premake projects; with -Deps also the client build/runtime dependencies (consent D3,
  sha256-pinned in deps-lock.json); with -Build a Release build of client (Win32) and server (x64).
  All the work is done by satk ({{WORKSPACE}}\tools\satk.cmd); this script only chains it.

  powershell -NoProfile -ExecutionPolicy Bypass -File {{WORKSPACE}}\engine\bootstrap.ps1 [-Deps] [-Build]
#>
[CmdletBinding()]
param(
    [switch] $Deps,
    [switch] $Build,
    [switch] $Offline,
    [string] $Satk = ''
)
$ErrorActionPreference = 'Stop'
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
if (-not $Satk) { $Satk = Join-Path (Split-Path -Parent $here) 'tools\satk.cmd' }
if (-not (Test-Path $Satk)) { throw "satk not found: $Satk (run {{WORKSPACE}}\tools\scripts\bootstrap.ps1 first)" }

$setupArgs = @('engine', 'setup', '--table')
if ($Deps) { $setupArgs += '--deps' }
if ($Offline) { $setupArgs += '--offline' }
& $Satk @setupArgs
if ($LASTEXITCODE) { exit $LASTEXITCODE }

& $Satk engine gen --table
if ($LASTEXITCODE) { exit $LASTEXITCODE }

if ($Build) {
    & $Satk engine build --project all --table
    if ($LASTEXITCODE) { exit $LASTEXITCODE }
}
& $Satk engine doctor --table
exit $LASTEXITCODE
