-- satk premake wrapper (WP-11, SPEC 4.12.2). Generated by `satk engine setup`; do not edit.
--
-- Runs the fork's own premake5.lua unchanged, but serves every download that the build
-- actions (install_cef, install_discord, install_unifont, install_data) would make from the
-- pinned copies in engine\deps (see engine\deps-lock.json). With SATK_OFFLINE=1 an unpinned
-- download fails instead of reaching the network.
--
-- Usage (cwd must be the fork root, the actions use cwd-relative paths):
--   cd {{WORKSPACE}}\engine\mtasa
--   utils\premake5.exe --file={{WORKSPACE}}\engine\satk-premake.lua install_cef

local ENGINE_DIR = _SCRIPT_DIR
local FORK_DIR = os.getenv("SATK_FORK") or path.join(ENGINE_DIR, "mtasa")
local LOCK_PATH = os.getenv("SATK_DEPS_LOCK") or path.join(ENGINE_DIR, "deps-lock.json")
local DEPS_DIR = path.join(ENGINE_DIR, "deps")
local OFFLINE = os.getenv("SATK_OFFLINE") == "1"

-- premake's http.escapeUrlParam turns "v3.4.3" into "v3%2E4%2E3": compare decoded URLs.
local function unescape(url)
	return (url:gsub("%%(%x%x)", function(h) return string.char(tonumber(h, 16)) end))
end

local pins = {}
do
	local f = io.open(LOCK_PATH, "r")
	if f then
		local text = f:read("*all")
		f:close()
		local data, err = json.decode(text)
		if data and data.items then
			for _, item in ipairs(data.items) do
				if item.url and item.file and item.sha256 then
					pins[unescape(item.url)] = item
				end
			end
		else
			print("satk: cannot parse " .. LOCK_PATH .. ": " .. tostring(err))
		end
	end
end

local real_download = http.download

http.download = function(url, file, options)
	local pin = pins[unescape(url)]
	if pin then
		local src = path.join(DEPS_DIR, pin.file)
		if not os.isfile(src) then
			return "satk: pinned file missing: " .. src, 0
		end
		if os.sha256_file then
			local h = os.sha256_file(src)
			if h ~= pin.sha256 then
				return "satk: sha256 mismatch for " .. src .. " (got " .. tostring(h) .. ")", 0
			end
		end
		local dir = path.getdirectory(file)
		if dir and dir ~= "" and dir ~= "." then
			os.mkdir(dir)
		end
		local ok, err = os.copyfile(src, file)
		if not ok then
			return "satk: copy failed: " .. tostring(err), 0
		end
		print("satk: served " .. url .. " from " .. pin.file)
		return "OK", 200
	end
	if OFFLINE then
		return "satk: offline and no pin for " .. url, 0
	end
	print("satk: WARNING unpinned download " .. url)
	return real_download(url, file, options)
end

include(path.join(FORK_DIR, "premake5.lua"))
